kubernetes-sigs/alibaba-cloud-csi-driver

- deploy/disk/disk-provisioner-attacher.yaml
container driver-registrar need to update nodeid into node annotations, so update node right should be added for csi-diskplugin serviceaccount
> fix bug: csi-diskplugin service account need update node right.

- deploy/disk/disk-plugin.yaml
- pkg/disk/disk.go
- pkg/disk/nodeserver.go
> Correct node id (in NodeInfo) for kube v1.12.X

- README.md
Since `v1.15.0-alpha.3` , the `--allow-privileged` is removed from kubelet options.
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#action-required-1
```
ACTION REQUIRED: The deprecated Kubelet flag --allow-privileged has been removed. Remove any use of --allow-privileged from your kubelet scripts or manifests.
```
> Add a note for `v1.15.0-alpha.3`

- deploy/lvm/lvm-plugin.yaml
the original version is not supported after v1.14 kubernetes
> change DS version to V1

- build/oss/csiplugin-connector.go
- build/oss/entrypoint.sh
* watchdog: csiplugin-connector will stop itself when no csi plugin is alive in 60 seconds.
* user can set env `PLUGINS_SOCKETS` to config the watchdog
* the watchdog is disabled default
> csiplugin-connector: add watchdog to watch csi plugin socket liveness

- pkg/metric/diskstat_collector.go
- pkg/metric/nfsstats_collector.go
- pkg/metric/pfsstat_collector.go
if nas disk pvc is unbound status, judge mountpath is empty.
> if nas disk pvc is unbound status, judge mountpath is empty.

- pkg/local/controllerserver.go
when csi run on large kubernetes cluster , controller/DeleteVolume may return error before waiting successfully delete lv. 
The extener-provisioner will retry. But the  controller/DeleteVolume not check the PV's annotations , update it to deleting.
> fix repeat update pv annotations

- pkg/disk/controllerserver.go
/kind bug
Add source pvc disk size to snapshot restore size
None
None
> Add source pvc disk size to snapshot restore size

- pkg/disk/nodeserver.go
- pkg/nas/nodeserver.go
- pkg/utils/util.go
kata runtime need mount options.
Fixes #
```release-note
record volume spec to vol_data.json file, and kata runtime can get spec from the file.
```
```docs
```
> volume spec to kata

- pkg/disk/controllerserver.go
- pkg/disk/disk.go
- pkg/disk/nodeserver.go
- pkg/disk/utils.go
A virtual nodes can manage pods in different zones, so CSI provisioner needs to support multi-zone nodes.
After this feature is enabled, CSI provisioner can find all zones supported by the multi-zone nodes, and add affinity information compatible with multi-zone nodes for PV during PV production.
> support multi-zones node for virtual node

- .dockerignore
/kind feature
- This PR will add a `.dockerignore` file. We need it to reduce the docker image build size and make the build faster. Also good for local development
> chore: Add `.dockerignore`

- pkg/disk/nodeserver.go
- pkg/ens/utils.go
- pkg/utils/util.go
/kind bug
Compatible with format issue of KMS encrypted disk, continue to format for an empty encrypt disk
None
None
None
None
> Fixed format issue of KMS encrypted disk

- build/lib/amd64-entrypoint.sh
/kind bug
Retry to install / upgrade ossfs when getting rpm lock failed.
Fixes #
Only fixed in AMD arch as rpm is not used in ARM arch entrypoint in current version.
```release-note
```
```docs
```
> add retry logic for ossfs install and upgrade for entrypoint of amd64

- pkg/pov/controller.go
/kind bug
Change condition of create mountpoint of hdfs filesystem
None
```release-note
```
```docs
```
> bugfix: Fix mountpoint judge condition

- pkg/disk/cloud.go
- pkg/disk/nodeserver.go
- pkg/disk/utils.go
/kind bug
When deciding the number of supported volumes for the disk driver, we are not counting for the already mounted volumes by the previous instance of this plugin.
This PR partially fixes this by calling `DescribeDisks` and counting for the disks provisioned by CSI. However, the static PVs are still not counted and would cause fewer volumes can be scheduled to this node.
Fixes #
```release-note
NONE
```
```docs
```
> Fix max volume count

- pkg/disk/cloud.go
- pkg/disk/controllerserver.go
/kind cleanup
ECS would refuse to delete the disk if it is just created and is initializing. Although k8s would retry in this case, it could prevent csi-sanity from properly cleaning up the disks created for testing. Also, retrying ourselves would hide this error from end-users.
```release-note
disk driver now retries deleting the disk if it is still initializing
```
```docs
```
> retry DeleteDisk if disk is still initializing

- pkg/dbfs/utils.go
- pkg/disk/disk.go
- pkg/disk/utils.go
- pkg/local/utils.go
- pkg/lvm/lvm.go
- pkg/lvm/utils.go
- pkg/mem/utils.go
- pkg/nas/controllerserver.go
- pkg/nas/nas.go
- pkg/nas/utils.go
- pkg/oss/nodeserver.go
- pkg/oss/utils.go
- pkg/utils/util.go
/kind bug
Fixes #792 
```release-note
```
```docs
```
> bugfix: use original URL from PV volume attributes if cannot get regionId for network policy check

- pkg/disk/constants.go
- pkg/disk/utils.go
- pkg/disk/utils_test.go
/kind cleanup
* use patch instead of update to avoid conflict and reduce traffic.
* backoff and retry for 1 hour if ECS or node patch failed.
* the labels are important for the scheduler. Make sure we can recover automatically if something goes wrong.
* also fix the incorrect retry logic
* add support for non-ACK node, skip query for disk types in this case.
```release-note
NONE
```
```docs
```
> refactor UpdateNode

- pkg/disk/controllerserver.go
- pkg/disk/nodeserver.go
- pkg/ens/nodeserver.go
- pkg/oss/controllerserver.go
/kind cleanup
Fix some low risk issue that prevent csi-sanity from producing reasonable result.
* `NodePublishVolume`: don't require `targetPath` to end with /mount
* in `CreateVolume`, `parameters` are optional and can be `nil`, fix the panic in this case
* `NodeUnpublishVolume` should delete `targetPath` as per [CSI spec](https://github.com/container-storage-interface/spec/blob/master/spec.md#nodeunpublishvolume):
> The SP MUST delete the file or directory it created at this path.
```release-note
NONE
```
```docs
```
> Changes to get reasonable csi-sanity test results

- pkg/dbfs/nodeserver.go
- pkg/disk/cloud.go
- pkg/disk/controllerserver.go
- pkg/disk/nodeserver.go
- pkg/disk/utils.go
- pkg/ens/controllerserver.go
- pkg/ens/nodeserver.go
- pkg/local/nodeserver.go
- pkg/pov/controller.go
/kind cleanup
the outcome is exactly the same, just be consistent in the codebase.
replace
```regex
status.Error\(codes\.(\w+),\s+fmt.Sprintf\((.+)\)\)
```
with
```
status.Errorf(codes.$1, $2)
```
```release-note
NONE
```
```docs
```
> unify status.Errorf usage

- pkg/disk/cloud.go
- pkg/disk/constants.go
- pkg/disk/controllerserver.go
- pkg/disk/nodeserver.go
/kind feature
If there are some disks created from a snapshot, that snapshot cannot be deleted without `force`. Because the disks cannot be re-initialized then. We don't support re-init, so just do force delete unconditionally.
Fixes #
```release-note
`forceDelete` snapshot parameter is no longer respected. Now snapshot can always be deleted even if there are volumes created from it.
```
```docs
```
> always force delete disk snapshot

- pkg/oss/coco.go
- pkg/oss/coco_test.go
- pkg/oss/nodeserver.go
- pkg/utils/kata/directvolume/direct_volume.go
- pkg/utils/kata/directvolume/utils.go
/kind feature
oss: support CoCo direct volume feature
Fixes #
https://github.com/kata-containers/kata-containers/blob/main/docs/design/direct-blk-device-assignment.md
https://github.com/kata-containers/kata-containers/issues/7943
https://github.com/kata-containers/kata-containers/pull/7965
https://github.com/confidential-containers/guest-components/pull/345/
```release-note
```
```docs
```
> oss: support CoCo direct volume feature

- pkg/utils/io.go
- pkg/utils/util.go
/kind bug
Fix IO limits not effective.
Affects:
- local(lvm), disk driver
- burstable, guaranteed QoS pod
logs that may reveal this bug:
```log
time="2023-10-18T11:05:12+08:00" level=error msg="WriteBps: Write file command(nsenter --mount=/proc/1/ns/mnt --ipc=/proc/1/ns/ipc --net=/proc/1/ns/net --uts=/proc/1/ns/uts sh -c 'echo 253:16 100 > /sys/fs/cgroup/blkio/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-poda3d10309_d144_479f_a391_2537fb1d9a41.slice/blkio.throttle.read_iops_device') error exit status 1"
```
```release-note
Fixed IO limits not effective on local(lvm)/disk PVs, on burstable/guaranteed QoS pods.
```
```docs
```
> Fix IO limits not effective

- pkg/disk/cloud.go
/kind bug
Narrow down reschedule scenario
Fixes #
```release-note
```
```docs
```
> Feature: narrow down reschedule scenario

- pkg/disk/constants.go
- pkg/disk/utils.go
/kind feature
Added support for ECS cloud_essd_entry disk category.
Fixes #
```release-note
Added support for ECS cloud_essd_entry disk category
```
```docs
```
> disk: support cloud_essd_entry category

- pkg/disk/nodeserver.go
- pkg/utils/mounter.go
/kind bug
We should unmount the 1.23- path even if no data disk present. Or kubelet will not unstage the volume.
#910 is not suitable for now, because we have no reliable way to remove volumeMount from csi-plugin DaemonSet in ACK.
Mount points in data disk are still always unmounted, because they also prevent kubelet from unstage the volume before 1.26 (See https://github.com/kubernetes/kubernetes/pull/112607 for the behaviour in 1.26+). Although this is incorrect: the unmount will propagate to `/var/lib/kubelet` and the real stage path is also unmounted. But we are already fixing this in NodePublishVolume. So, I left it as it is for now.
We do not mount v2 path in NodeStageVolume if v1 path is present, maybe trying to prevent two mounts to exists simultaneously. However, this does not …
> disk: fix unmountDuplicateMountPoint to handle no data disk node

- pkg/disk/nodeserver.go
- pkg/disk/utils.go
/kind bug
fix parameter checks in NewNodeServer
Fixes #
```release-note
NONE
```
```docs
```
> disk: fix parameter checks in NewNodeServer

- build/lib/amd64-entrypoint.sh
- build/lib/arm64-entrypoint.sh
/kind bug
Avoid daily updatedb scan on kublet-rootdir triggered by mlocate.
Fixes #
```release-note
```
```docs
```
> fix: configure mlocate cron.daily

- build/multi/Dockerfile.multi.asi
/kind cleanup
Fixes #
```release-note
```
```docs
```
> build(asi): update dockerfile

- pkg/local/client/grpc.go
- pkg/local/controllerserver.go
- pkg/utils/util.go
/kind feature
local: allow volume to be removed from deleted node
Also add an event for this.
Fixes #
```release-note
local volumes can be automatically removed from deleted nodes. The data is left intact, Admins should take care of them.
```
```docs
```
> local: allow volume to be removed from deleted node

- build/fuse-clients/ossfs/install-ossfs.sh
- pkg/mounter/ossfs.go
fix: use "mime" key to compatible with s3fs
Fixes #
```release-note
```
```docs
```
> fix: use "mime" key to compatible with s3fs

- pkg/disk/cloud.go
- pkg/disk/controllerserver.go
- pkg/disk/utils.go
- pkg/disk/utils_test.go
/kind cleanup
Avoid repeated split and join.
The original `validateDiskPerformaceLevel` does not validate the input if it does not contains comma. Fixed this.
```release-note
NONE
```
```docs
```
> store disk type and performance level as slice

- pkg/metric/collector.go
- pkg/metric/kubelet_stats_summary_collector.go
/kind bug
Fixes #
kubelet stats summary collector may panic in k8s 1.20 version.
```release-note
```
```docs
```
> fix metrics collector panic

- pkg/disk/cloud.go
- pkg/disk/utils.go
/kind bug
disk: fix config file leakage if VolumeDevice is detached from DeleteVolume.
When kubelet restarts, it will call StageVolume again. and if the leakage does happen, we will detach and attach the disk again, because `IsDeviceUsedOthers` returns true, which is dangerous if the user of this disk is running.
Fixes #
```release-note
Fix potential I/O error after kubelet restarts.
```
```docs
```
> disk: fix config file leakage if VolumeDevice is detached from DeleteVolume

- pkg/mounter/ossfs.go
users can just modified configmap to debug ossfs, instead redeploying pvs, pvcs and apps.
Fixes #
```release-note
```
```docs
```
> support debug level log for ossfs in configmap

- deploy/ecs/csi-plugin.yaml
- deploy/ecs/csi-provisioner.yaml
- pkg/cloud/ecsinterface.go
- pkg/cloud/ecsmock.go
- pkg/cloud/metadata/metadata.go
- pkg/cloud/metadata/metadata_test.go
- pkg/common/constants.go
- pkg/disk/cloud.go
- pkg/disk/disk.go
- pkg/disk/nodeserver.go
- pkg/disk/utils.go
- pkg/disk/utils_test.go
- test/csi-sanity/csi-sanity-disk.yaml
/kind feature
/kind api-change
Volume count detection now also works for static PV. 
We detect whether a disk is managed by us by reading k8s node resource, instead of disk tag.
This makes OpenAPI access on node mandatory. We cannot startup if we cannot access OpenAPI.
set DISK_ALLOW_ALL_TYPE env to skip this.
Also makes KUBE_NODE_NAME env mandatory.
Fixes #
```release-note
action required: make sure you have KUBE_NODE_NAME env set for plugin Pod.
action required: make sure `ecs:DescribeInstanceTypes` and `ecs:DescribeDisks` RAM permission is granted to plugin.
a new tag csi.alibabacloud.com/volume-name is added to EBS disk
```
```docs
```
> disk: refined volume count detection

- pkg/common/constants.go
- pkg/disk/cloud.go
- pkg/disk/constants.go
- pkg/disk/controllerserver.go
/kind feature
/kind design
Automatically add 3 more tags to every ECS snapshot:
- ack.aliyun.com: current ACK cluster ID
- csi.alibabacloud.com/snapshot/name
- csi.alibabacloud.com/snapshot/namespace
Also allow users to add custom tags.
User should specify "snapshotTags/tagKey: tagValue" in VolumeSnapshotClass to add tag "tagKey: tagValue".  This design allows arbitrary keys and values, compared with the design of disk tags, which does not allow "," in key or value, or ":" in key.
If this design works fine, we can also implement this on disk tags.
Fixes #900 
```release-note
3 more tags are added to every new ECS snapshot:
- ack.aliyun.com: current ACK cluster ID
- csi.alibabacloud.com/snapshot/name
- csi.alibabacloud.com/snapshot/namespace
You can also add custom tag "tagKey: tagValue" …
```
> disk: add tags to ECS snapshot

- pkg/disk/nodeserver.go
- pkg/ens/nodeserver.go
/kind bug
ensure we retry set IO limit after it failed.
Fixes #
```release-note
Fix a bug that IO limit setting may be not effective.
```
```docs
```
> disk: set IO limit before mount

- pkg/disk/attachdetach_slot.go
- pkg/disk/attachdetach_slot_test.go
- pkg/disk/cloud.go
- pkg/disk/controllerserver.go
- pkg/disk/disk.go
- pkg/disk/nodeserver.go
/kind feature
Avoid backoff caused by InvalidOperation.Conflict thus speed up attaching.
Prioritize detach over attach to avoid InstanceDiskLimitExceeded error with best effort
set DISK_SERIAL_ATTACH env to opt-in this behaviour in controller
Fixes #
This is necessary to pass the external-storage test in k/k repository. Or we will almost certainly get timeout for volume not attached in 5 minutes.
```release-note
Attach/detach multiple volumes to one node at the same time is optimized to have higher throughput, and less conflict error.
```
```docs
```
> disk: wait to serialize attach & detach

- build/lib/csiplugin-connector.go
- build/multi-private/csiplugin-connector.go
- main.go
- pkg/cpfs/cpfs.go
- pkg/dbfs/controllerserver.go
- pkg/dbfs/dbfs.go
- pkg/dbfs/nodeserver.go
- pkg/dbfs/utils.go
- pkg/disk/bdf.go
- pkg/disk/cloud.go
- pkg/disk/constants.go
- pkg/disk/disk.go
- pkg/ens/ens.go
- pkg/ens/nodeserver.go
- pkg/local/local.go
- pkg/local/utils.go
- pkg/nas/utils.go
- pkg/om/blockvolume.go
- pkg/oss/controllerserver.go
- pkg/oss/utils.go
- pkg/utils/mounter.go
- pkg/utils/util.go
/kind cleanup
remove some of the codes that is not used anywhere.
Fixes #
```release-note
NONE
```
```docs
```
> batch dead code removal

- pkg/cloud/metadata/ecs.go
- pkg/cloud/metadata/metadata.go
- pkg/disk/disk.go
/kind cleanup
/kind bug
support running provisioner without ECS metadata
Fixes #
```release-note
NONE
```
```docs
```
> disk: support running provisioner without ECS metadata

- pkg/local/capacity.go
/kind bug
Fix float64 conversion
Fixes #
```release-note
```
```docs
```
> bug: fix string float conversion

- pkg/disk/nodeserver.go
- pkg/disk/utils.go
/kind cleanup
to comply with CSI
Fixes #
```release-note
NONE
```
```docs
```
> disk/NodeExpandVolume: return NotFound if VolumePath not found

- build/fuse-clients/ossfs/install-ossfs.sh
- pkg/metric/fuse_stat_collector.go
- pkg/mounter/ossfs.go
- pkg/oss/nodeserver.go
- pkg/utils/util.go
/kind bug
enable containerized ossfs metrics server
Fixes #
```release-note
```
```docs
```
>  fix: containerized ossfs metrics

- pkg/oss/nodeserver.go
- pkg/oss/utils.go
- pkg/oss/utils_test.go
/kind feature
In current version, CSI will not check protocol of ossfs URL. Then, ossfs will use default protocol (http) if it is not specified explicitly. 
In this PR, protocol will be set by CSI. If instance needs to access OSS with public endpoint, use https as default protocol instead.
Fixes #
```release-note
```
```docs
```
> oss-perf: modify default protocol for ossfs URL

- pkg/disk/utils.go
- pkg/ens/utils.go
/kind cleanup
User may be using sata or nvme local volume as systemdisk. so this check is invalid in some scanario. According to csi current logic after we disable system disk check, it will return normally if device is mounted on "/" . have no influence with current node
Fixes #
```release-note
```
```docs
```
> feature: remove system disk check failed

- pkg/nas/cloud/nas_client_v1.go
- pkg/nas/cloud/nas_client_v2.go
- pkg/nas/cloud/utils.go
/kind bug
Fixes #
```release-note
```
```docs
```
> fix(nas): do not set vpc endpoint for all regions

- pkg/disk/utils.go
- pkg/disk/utils_test.go
/kind bug
local disks do not occupy the quota shown in DiskQuantity
Fixes #
```release-note
Fix that fewer disks can be scheduled to instances that have local disks.
```
```docs
```
> disk: only count cloud disks

- pkg/disk/nodeserver.go
/kind feature
1. Add check if block device size is as expect
2. remove filesystem resize check 
Fixes # None
None
```release-note
```
```docs
```
> feat: organize node expand logics

- pkg/disk/disk.go
- pkg/disk/nodeserver.go
- pkg/disk/utils.go
- pkg/disk/utils_test.go
/kind bug
/kind cleanup
fix NodeExpandVolume always return error
remove unnessesary statfs
remove float math
remove the unused parameter FILE_SYSTEM_LOSE_PERCENT
optimize error message
fix false error if req.CapacityRange is not specified
Fixes #1008 
Fixes 377c9e9bce468c996426da502fc1e157a13ac5f7
```release-note
FILE_SYSTEM_LOSE_PERCENT env is now deprecated and not used.
```
```docs
```
> disk: fix and cleanup NodeExpandVolume

- pkg/disk/device_manager.go
- pkg/disk/device_manager_test.go
- pkg/disk/nodeserver.go
- pkg/disk/utils.go
/kind bug
Do not rely on the device path to determine partition. Read sysfs instead.
Fixes CSI sanity failure:
Volume d-2ze2vto7mqwoffxi2uh9 GetDeviceRootAndIndex with error Device /dev/disk/by-id/virtio-2ze2vto7mqwoffxi2uh9 has error format more than one digit locations
Fixes: 9a71d43bb92d866497e6da11ea8281bd940d5b27
```release-note
NONE
```
```docs
```
> disk: fix partition detection

- deploy/chart/templates/controller.yaml
- deploy/chart/values-nonecs.yaml
- deploy/chart/values.yaml
- docs/install.md
- docs/nas-dynamic.md
/kind bug
To fix panic in NAS controller because of missing region ID.
Dynamic NAS is not supported by default on non-ECS cluster.
Add a regionID value, in case someone want to hack with this. Note that currently deleting NAS volume relies on storage-operator, which is not supported on non-ECS cluster. So we do not recommend this in the doc.
Fixes #
/cc @tydra-wang 
```release-note
NONE
```
```docs
```
> docs,helm: disable controller on non-ECS

- pkg/disk/device_manager_test.go
- pkg/disk/utils.go
/kind bug
Remove the redundant check in checkRootAndSubDeviceFS, all callers have already ensured sub device.
Fix the error:
NodeStageVolume: Attach volume: d-2ze015ceoqguma3f7gaq with error: AttachDisk: disk device cannot be found in node, diskid: d-2ze015ceoqguma3f7gaq, deviceName: , err: volume d-2ze015ceoqguma3f7gaq resolved to device /dev/disk/by-id/nvme-Alibaba_Cloud_Elastic_Block_Storage_2ze015ceoqguma3f7gaq, but adapt partition failed: DeviceNotAvailable: input devices is not root&sub device path: /dev/disk/by-id/nvme-Alibaba_Cloud_Elastic_Block_Storage_2ze015ceoqguma3f7gaq, /dev/nvme2n1p1
Also add support for parted disk with NVMe driver.
Fixes: 9a71d43bb92d866497e6da11ea8281bd940d5b27
Fixes #
```release-note
NONE
```
```docs
```
> disk: fix error when mounting parted disks

- pkg/disk/utils.go
/kind cleanup
avoid two level of status.Error
Fixes #
```release-note
NONE
```
```docs
```
> avoid two level of status.Error

- pkg/cloud/ecsinterface.go
- pkg/cloud/ecsmock.go
- pkg/disk/cloud.go
- pkg/disk/cloud_test.go
- pkg/disk/controllerserver.go
/kind cleanup
disk/ListSnapshots: refactor to comply with CSI
workaround that ECS don't support max_entries < 10
Fixes all CSI-sanity cases of ListSnapshots:
- listsnapshots [controller server] [it] should return appropriate values (no optional values added)
- listsnapshots [controller server] [it] should return empty when the specified snapshot id does not exist
- listsnapshots [controller server] [it] should return snapshots that match the specified source volume id
- listsnapshots [controller server] [it] should return empty when the specified source volume id does not exist
- listsnapshots [controller server] [it] check the presence of new snapshots in the snapshot list
- listsnapshots [controller server] [it] should return next token when a limited number of entries are requested …
> disk/ListSnapshots: refactor to comply with CSI

- pkg/nas/nodeserver.go
- pkg/nas/utils.go
/kind bug
As vol_data.json could be recreated by kubelet when mounter.SetUpAt is executed twice, csi should always try to update it when NodePublishVolume.
Fixes #
```release-note
```
```docs
```
> Fix volume setup for rund 2.0

- pkg/disk/cloud.go
- pkg/disk/controllerserver.go
- pkg/disk/utils.go
- pkg/disk/utils_test.go
/kind api-change
/kind feature
Reject CreateVolume if capability cannot be supported: MULTI_NODE_MULTI_WRITER
and MULTI_NODE_SINGLE_WRITER for mount volumes.
Require MultiAttach to be enabled in parameters if multi-node access is requested.
We do not enable it automatically because multi-attach implies additional limits,
which may be unexpected to user.
Also implement the ValidateVolumeCapabilities controller RPC call.
Fixes CSI sanity case:
* controller service [controller server] validatevolumecapabilities [it] should fail when the requested volume does not exist
PVC with `volumeMode: Filesystem` and `accessModes: [ ReadWriteMany ]` will fail with this event:
Warning  ProvisioningFailed    2s (x3 over 3s)  diskplugin.csi.alibabacloud.com_csi-provisioner-647f8bccfb-w22zq_d72ba154-98bf-4c6 …
> disk: verify VolumeCapabilities

- deploy/chart/templates/controller.yaml
- deploy/chart/templates/plugin.yaml
/kind cleanup
remove hostPath /mnt from controller. It is no longer needed since 33875a5bf3 (refactor nas plugin and support accesspoint).
local driver still needs this for quota path.
Fixes #
/cc @tydra-wang 
```release-note
NONE
```
```docs
```
> helm: nas driver no longer needs /mnt

- deploy/chart/templates/plugin.yaml
/kind bug
deploy: revert the selector of DaemonSet of default node pool
This field is immutable, existing users cannot upgrade to the new labels.
deploy: add a common label to daemonset
Fixes d8de0a61316932eaee4cb80a65401bd25093b260
```release-note
NONE
```
```docs
```
> Fix helm upgrade

- build/lib/init.sh
yum install is not idempotent, so we need to check if the package is already installed. yum also fails if the already installed version is newer, so we need to downgrade. dnf do all of these automatically.
/kind bug
Fixes c67535f358679194c34cac29793ab23fafb0c273
```release-note
NONE
```
```docs
```
> init: fix restart and downgrade for yum

- pkg/nas/nodeserver.go
- pkg/nas/utils.go
Fix auto creation of subpath for cpfs
/kind cleanup
Fixes #
```release-note
```
```docs
```
> no longer use /mnt as tmp mount path

- pkg/disk/bdf.go
- pkg/disk/device_manager.go
- pkg/disk/device_manager_test.go
- pkg/disk/nodeserver.go
- pkg/disk/utils.go
- pkg/disk/utils_test.go
- pkg/utils/io/io_darwin.go
- pkg/utils/io/io_linux.go
/kind bug
to fix the issue that when DISK_AD_CONTROLLER is enabled and disk is detaching, MaxVolumesPerNode may be smaller than expected
Fixes #
```release-note
fixed that when DISK_AD_CONTROLLER is enabled and disk is detaching, MaxVolumesPerNode may be smaller than expected
```
```docs
```
> disk: use xattr to check if the disk is managed by us

- pkg/disk/attachdetach_slot.go
- pkg/disk/attachdetach_slot_test.go
- pkg/disk/cloud.go
- pkg/disk/disk.go
- pkg/features/features.go
/kind feature
When parallel attach is enabled on ECS, parallel detach is still not supported. 
We should synchronize only detach operations for performance.
Fixes #
```release-note
new feature gate DiskParallelAttach for users who enabled ECS concurrency attach
```
```docs
```
> disk: serial detach ad-slot

- pkg/disk/cleanup.go
- pkg/disk/nodeserver.go
/kind bug
These old mountpoints can block volumes cleanup.
We do the cleanup at NodeStageVolume, so that the cleanup is performed once the v1.24 kubelet is upgraded and up.
Or if no volume is mounted, the cleanup is performed at first volume mount.
Fixes #
```release-note
old volume mount path from v1.22 kubelet is automatically cleaned up
```
```docs
```
> disk: cleanup old globalmount mounts

- pkg/cloud/ecsinterface.go
- pkg/cloud/ecsmock.go
- pkg/disk/category.go
- pkg/disk/cloud.go
- pkg/disk/cloud_test.go
- pkg/disk/constants.go
- pkg/disk/controllerserver.go
- pkg/disk/utils.go
- pkg/disk/utils_test.go
/kind cleanup
**disk: aggregate category metadata into one file**
We will not forget something when adding new category.
**disk: refactor create disk**
Use hash of diskName as client token to ensure only one disk is created for one PVC.
If we see IdempotentParameterMismatch, fall back to DescribeDisks to fetch existing disk.
When CreateDisk fails, it records the client token only for some case, but we don't know which.
If we use a new token for retry, we are risking creating duplicated disks.
If we reuse the same token. the retry may fail for IdempotentParameterMismatch.
So fetching the existing disk and checking it ourselves seems to be the only choice.
Fixes #
Replaces #876
```release-note
The client token generation algorithm changed. There is a very small chance that a duplicated disk …
```
> disk: refactor create disk

- pkg/disk/nodeserver.go
- pkg/disk/utils.go
- pkg/disk/utils_test.go
- pkg/utils/io/device.go
/kind cleanup
should reduce false warnings about unable to read xattr
Fixes #
```
time="2024-08-06T20:34:04+08:00" level=warning msg="getVolumeCount: failed to get xattr of core, assuming not managed by us: operation not supported"
time="2024-08-06T20:34:04+08:00" level=warning msg="getVolumeCount: failed to get xattr of fd, assuming not managed by us: operation not supported"
time="2024-08-06T20:34:04+08:00" level=warning msg="getVolumeCount: failed to get xattr of initctl, assuming not managed by us: no such file or directory"
time="2024-08-06T20:34:04+08:00" level=warning msg="getVolumeCount: failed to get xattr of log, assuming not managed by us: no such file or directory"
time="2024-08-06T20:34:04+08:00" level=warning msg="getVolumeCount: failed to get xattr of stderr, assuming not …
```
> disk: skip read xattr for files other than block device

- deploy/chart/templates/_utils.tpl
- deploy/chart/templates/plugin.yaml
ACK has issue merging the new template when upgrading very old installations that has no last-applied-configuration annotations. This will cause duplicated volumeMounts entries, and double the number of bind mount on kubeletRootDir on the host at every csi-plugin restart.
Fixes #1121 
Not relevant to users who only use helm chart.
Net change of the rendered YAML
```diff
--- a/ack/templates/default/csi-plugin.yaml
+++ b/ack/templates/default/csi-plugin.yaml
@@ -327,7 +327,8 @@ spec:
containerPort: 11260
volumeMounts:
- name: kubelet-dir
-              mountPath: "/var/lib/kubelet"
+              # keep the trailing slash to be compatible with old ACK installations
+              mountPath: "/var/lib/kubelet/"
mountPropagation: "Bidirectional"
- name: disk-plugin-dir
mountPath: …
```
> deploy: cleanup kubelet root dir and add slash to volumeMounts

- pkg/disk/cloud.go
- pkg/disk/constants.go
- pkg/disk/controllerserver.go
/kind feature
ECS snapshot of ESSD is always instantly assessable, without extra fee. OpenAPI ETA 2023-10-12
Fixes #
```release-note
After 2023-10-12, ECS snapshot of ESSD is always instantly assessable, without extra fee. Related features are removed from CSI. Existing setup should continue to work. These features includes:
* VolumeSnapshotClass parameter `snapshotType=InstantAccess`
* VolumeSnapshotClass parameter `instantAccessRetentionDays`
* VolumeSnapshot annotation `storage.alibabacloud.com/ia-snapshot: true`
* VolumeSnapshot annotation `storage.alibabacloud.com/ia-snapshot-ttl`
```
```docs
```
> disk: remove instant access snapshot params

- pkg/common/constants.go
- pkg/disk/category.go
- pkg/disk/cloud.go
- pkg/disk/cloud_test.go
- pkg/disk/controllerserver.go
- pkg/disk/nodeserver.go
- pkg/disk/utils.go
/kind feature
disk: support for EED
Fixes #
EED only supports WaitForFirstConsumer volumeBindingMode. It will be bound to a single node on CreateVolume.
EED only requires binding after first attach, but we cannot modify the PV affinity after creation.
If VK creates an EED, we cannot prevent the next pod using it from being scheduled to ECS. So the only valid use-case with EED and VK is ephemeral volume.
```release-note
Support for Elastic Ephemeral Disk (EED)
```
```docs
```
> disk: support for EED

- pkg/mounter/fuse_pod_manager.go
- pkg/mounter/fuse_pod_manager_test.go
- pkg/mounter/ossfs.go
- pkg/mounter/ossfs_test.go
Ossfs's default dbglevel is crit, which means users will not get any error message during mounting.
As Ossfs is containerized, I suggest setting dbglevel to err by default by CSI. 
Fixes #
```release-note
```
```docs
```
> OSS: set default ossfs default log level to err

- pkg/nas/internal/config.go
- pkg/nas/subpath_controller.go
Use ENABLE_NAS_RECYCLEBIN_CHECK environment variable to enable it.
/kind feature
Recycle bin check when deleting subpath may significantly increase user costs on NAS.
Fixes #
```release-note
```
```docs
```
> Disable recycle bin check when deleting subpath

- pkg/disk/utils.go
/kind feature
They also occupy the DiskQuantity.
Fixes #
```release-note
Consider already attached EED when calculating MaxVolumesPerNode
```
```docs
```
> disk: also count EED when getAttachedCloudDisks

- pkg/oss/nodeserver.go
trimspace for aksk in nodePublishSecretRef to deal with the copy error with unexpected `/n`
Fixes #
```release-note
```
```docs
```
> oss: trimspace for ak&sk

- pkg/mounter/fuse_pod_manager.go
/kind bug
The ACK managed node pool auto-repair task evicts pods on the `notReady` node, including OSSFS pods. ACK may uncordon the node before all pod terminated. If new pods are scheduled to the node before that, the OSSFS pod cannot be recreated as the previous VolumeAttachment is not deleted. Therefore, we need to configure ACK to skip evicting OSSFS pods by using the label `alibabacloud.com/drain-pod=skip`.
Fixes #
```release-note
```
```docs
```
> Make ack drain skip fuse pods 

- pkg/disk/cloud.go
- pkg/disk/controllerserver.go
/kind cleanup
The default timeout of external-attacher is only 15s. Timeout is common. We can save some OpenAPI calls after timeout.
Fixes #
```release-note
NONE
```
```docs
```
> disk: cancel waiting for attach/detach when GRPC cancelled

- pkg/disk/attachdetach_slot.go
- pkg/disk/attachdetach_slot_test.go
- pkg/disk/nodeserver.go
- pkg/utils/volume_locks.go
/kind bug
If the umount takes extremely long time and the NodeUnstageVolume RPC times out, kubelet may invoke NodeStageVolume when it retries and we may mistake an unmounting disk as a good one. This lock only protects us in one process. But fortunately, when restarting CSI, Kubernetes will wait for the previous process to exit before starting the new one, even if it stucks in uninterruptible syscall (D state). So, we will not have multiple processes on the same node and the lock should be safe enough.
Note that there is still small chance that the previous attach/detach OpenAPI is invoked by the terminated CSI process, but the state returned by DescribeDisks is not updated yet. We should fix this by switch attach/detach to controller.
Fixes #
```release-note
Fix unintended disk detach …
```
> disk: avoid concurrent operation on the same disk

- build/mount-proxy/Dockerfile
- deploy/chart/values.yaml
- pkg/mounter/ossfs.go
- pkg/oss/controllerserver.go
- pkg/oss/nodeserver.go
- pkg/oss/utils.go
- pkg/oss/utils_test.go
/kind cleanup
/kind feature
cleanup: merge options parsing functions for provisioner and plugin
core: bump ossfs version to 1.91.4.ack.1
feat: support signature v4, which is necessary for special regions.
Fixes #
```release-note
```
```docs
```
> oss: ossfs bump to 1.91.4 and support OSS signature v4

- pkg/common/constants.go
- pkg/nas/filesystem_controller.go
- pkg/nas/sharepath_controller.go
- pkg/oss/controllerserver.go
- pkg/oss/nodeserver.go
- pkg/oss/utils.go
- pkg/oss/utils_test.go
/feature
From 1.91+ version, ossfs support to mount a non-existed path (object) in OSS server, making it possible to support `subpath` mode as NAS for cnfs-oss.
Fixes #
```release-note
```
```docs
```
> oss: cnfs-oss support use subpath 

- pkg/disk/controllerserver.go
- pkg/disk/utils.go
- pkg/features/features.go
This feature is broken, and we should provide a way to escape. Protentially disable this feature by default in the future.
/kind deprecation
/kind feature
Fixes #
```release-note
Use DisableExpandAutoSnapshot feature gate to disable the broken expand auto snapshot feature.
```
```docs
```
> disk: add a feature gate to disable expand auto snapshot

- build/multi/Dockerfile.multi
- build/multi/Dockerfile.multi.asi
- pkg/cloud/metadata/k8s.go
- pkg/cloud/metadata/metadata.go
- pkg/disk/bdf.go
- pkg/disk/device_manager.go
- pkg/disk/nodeserver.go
Fixes #
```release-note
```
```docs
```
> Check VBM node type automatically and support csi rund 3.0 protocol

- pkg/disk/cloud.go
- pkg/disk/controllerserver.go
- pkg/disk/nodeserver.go
/kind cleanup
even if !ADControllerEnable, we still attach multi-attach disk on controller. So we replace it with a new parameter fromNode to ensure no node related work is performed on controller.
Fixes #
```release-note
None
```
```docs
```
> disk: distinguish attach from node/controller

- deploy/chart/templates/controller.yaml
- deploy/chart/templates/plugin.yaml
- main.go
- pkg/disk/cloud.go
- pkg/disk/controllerserver.go
- pkg/disk/disk.go
- pkg/disk/nodeserver.go
- pkg/ens/ens.go
- pkg/metric/collector.go
- pkg/metric/metric.go
- pkg/nas/nas.go
- pkg/nas/nas_test.go
- pkg/oss/oss.go
- pkg/pov/pov.go
- pkg/utils/util.go
- pkg/utils/util_test.go
/kind cleanup
/kind feature
/kind deprecation
Every driver supports enable/disable node or controller service, with unified interface.
deprecate SERVICE_TYPE env
deprecate -run-as-controller flags
introduce -run-controller-service and -run-node-service, allowing controller and node service to be enabled/disabled independently.
Fixes #
```release-note
new -run-controller-service and -run-node-service flags are introduced, -run-as-controller and SERVICE_TYPE env are deprecated.
```
```docs
```
> unify node/controller service enabling

- cmd/csi-agent/main.go
/kind bug
CSI-agent is not invoked by kubelet, so there is no usual kubelet directory structure.
Fixes #
```release-note
NONE
```
```docs
```
> csi-agent: disable sub-directory check in NodeServerWithValidator

- pkg/disk/bdf.go
- pkg/disk/nodeserver.go
- pkg/disk/nodeserver_test.go
- pkg/utils/fake_mounter.go
- pkg/utils/rund/directvolume/utils.go
/kind bug
Confirm if volume is in use by runD after kubelet restarts
None
```release-note
```
```docs
```
> Fix kubelet restart grpc calling bugs of runD

- pkg/oss/nodeserver.go
- pkg/oss/nodeserver_test.go
/kind bug
`vpc100-oss-cn-beijing.aliyuncs.com` is the deprecated internal endpoint. automatically patch `-internal` will make it invalid, this PR will skip all endpoints with `vpc100` prefix. 
Fixes #
```release-note
```
```docs
```
> oss: do not modify vpc100 endpoint

- pkg/disk/nodeserver.go
- pkg/ens/nodeserver.go
- pkg/utils/mounter.go
- pkg/utils/mounter_test.go
/kind cleanup
Replaced with os.MkdirAll(), the behaviour should not change.
Fixes #
```release-note
NONE
```
```docs
```
> remove mounter.EnsureFolder()

- deploy/chart/values.yaml
Fix panic with NAS static storage class name
Switch to distroless
Fixes #
```release-note
Fix panic with NAS static storage class name
```
```docs
```
> deploy: bump external-provisioner to v5.0.3-aliyun

- pkg/mounter/fuse_pod_manager.go
- pkg/oss/controllerserver.go
…atus
/kind feature
Make troubleshooting easiler.
Fixes #
```release-note
```
```docs
```
> Make the OSSFS pod name visible in VolumeAttachment

- build/multi/Dockerfile.multi
- build/multi/Dockerfile.multi.asi
- pkg/disk/nodeserver.go
- pkg/disk/sfdisk/expand.go
- pkg/disk/sfdisk/expand_test.go
- pkg/utils/os/exec.go
- pkg/utils/os/exec_test.go
/kind bug
growpart is a shell script, and we don't have shell now in our image.
Fixes: af7a885cb5d0c5be15e22618738cf187aea1d9a7
Fixes: #1133 
```release-note
NONE
```
```docs
```
> disk: call sfdisk directly to expand partition

- pkg/metric/utils.go
- pkg/metric/utils_test.go
/kind bug
Fixes:
```
E1216 18:26:45.999408  499952 disk_stat_collector.go:462] Get pv /var/lib/kubelet%!(EXTRA string=/plugins/kubernetes.io/csi/%s/%x/globalmount, string=diskplugin.csi.alibabacloud.com, [32]uint8=[209 131 97 74 247 233 227 64 50 28 36 159 14 55 30 150 32 40 33 38 228 79 208 24 110 25 70 70 17 3 96 219]) metrics from kubelet is failed, err: no such file or directory
```
Fixes #1044 
```release-note
Fix that disk size metrics are missing
```
```docs
```
> metric/disk: fix disk size reporting

- pkg/disk/utils.go
- pkg/disk/utils_test.go
/kind cleanup
It is only used in test. And we can just use os.MkdirAll
Fixes #
```release-note
NONE
```
```docs
```
> disk: remove createDest

- pkg/disk/nodeserver.go
/kind cleanup
We currently checking for volumePath to determine whether it is a block volume. But we should not do that, the path is implementation details of kubelet.
This should fix csi-sanity test case
Fixes #
```release-note
NONE
```
```docs
```
> disk: also check for VolumeCapability when expand

- pkg/disk/nodeserver.go
/kind cleanup
We have instance types that allows >64 disks. For example, OpenAPI DescribeInstanceTypes(MinimumDiskQuantity=66) returns 25 result.
Fixes #
```release-note
Removed max value limit of env MAX_VOLUMES_PERNODE
```
```docs
```
> disk remove MaxVolumesPerNodeLimit

- pkg/disk/constants.go
- pkg/disk/controllerserver.go
- pkg/disk/utils.go
- pkg/features/features.go
/kind bug
/kind deprecation
Following up #1182 , remove this function since it is not working and will block resizing.
preserve the function of deleting snapshot on successful resize for one more version, to avoid leaking snapshots.
Fixes #
```release-note
DisableExpandAutoSnapshot feature gate is now locked to true, auto snapshot on resizing is no longer supported
```
```docs
```
> disk: remove expand auto snapshot

- pkg/cloud/throttle/throttle.go
- pkg/cloud/throttle/throttle_test.go
- pkg/disk/batcher/interface.go
- pkg/disk/batcher/low_latency.go
- pkg/disk/batcher/low_latency_test.go
- pkg/disk/cloud.go
- pkg/disk/controllerserver.go
- pkg/disk/desc/describe.go
- pkg/disk/desc/testing/fake.go
- pkg/disk/disk.go
- pkg/disk/nodeserver.go
- pkg/disk/waitstatus/batched.go
- pkg/disk/waitstatus/batched_test.go
- pkg/disk/waitstatus/client.go
- pkg/disk/waitstatus/interface.go
- pkg/disk/waitstatus/interface_test.go
- pkg/disk/waitstatus/simple.go
/kind feature
/kind cleanup
disk: introduce DiskStatusWaiter
A central place for all disks pending status changes (attaching/detaching).
Waiter will poll disk status in batch and wake up the caller if the status has changed.
The motivation is reducing OpenAPI call count, to avoid triggering throttling, thus improve system throughput.
Also include a simple fallback waiter to support multi-tanent use-case.
Shared disk support is best effort, since we cannot create new shared disks for test now.
Fixes #
```release-note
If AD-controller enabled, the number of DescribeDisks requests on a busy cluster will be reduced greatly.
```
```docs
```
> disk: DescribeDisks auto batching

- build/gather-node-deps.sh
- hack/base-image-deps.txt
Missing /etc/netconfig causes 'mount.nfs: Protocol not supported' error.
/kind bug
Missing /etc/netconfig causes 'mount.nfs: Protocol not supported' error.
Fixes #
```release-note
```
```docs
```
> fix(build): mount.nfs failed

- deploy/chart/templates/plugin.yaml
/kind cleanup
Increase the limit to be equal to the csi-plugin container. Making the limit of init container smaller than main container does not have any benefits.
Fixes #
We've seem OOMs at init container. Not sure what has changed and triggered this issue yet.
```release-note
NONE
```
```docs
```
> deploy: increase the limit of init container

- pkg/disk/cloud.go
- pkg/disk/device_manager.go
- pkg/disk/device_manager_test.go
- pkg/disk/nodeserver.go
/kind cleanup
/kind flake
Even after OpenAPI returns Attached status, the device may not be available in OS immediately. We wait for 10s to reduce noisy error events.
Fixes #
Reduce flakes in csi-sanity, which will not retry.
```release-note
NONE
```
```docs
```
> disk: wait for device to appear on attach

- pkg/disk/bdfcheck.go
- pkg/disk/cloud.go
- pkg/disk/controllerserver.go
- pkg/disk/nodeserver.go
- pkg/disk/utils.go
- pkg/ens/nodeserver.go
- pkg/ens/utils.go
- pkg/nas/nodeserver.go
- pkg/nas/subpath_controller.go
- pkg/oss/controllerserver.go
- pkg/oss/nodeserver.go
/kind cleanup
This should avoid any accidental injection of format specifier.
- log before event is not necessary. EventRecorder will do so.
- log before return GRPC error is not necessary. We have interceptor to do so.
resolves all warnings like:
non-constant format string in call to k8s.io/klog/v2.Errorf
Fixes #
```release-note
NONE
```
```docs
```
> Cleanup all non-constant printf format string

- pkg/disk/controllerserver.go
/kind cleanup
Disk attachment of ECI instances is not managed by us, it is automatically detached when the container exits. We should not be asked to detach. This is a safeguard just in case something goes wrong.
Fixes #
```release-note
NONE
```
```docs
```
> disk: refuse to delete disk on ECI

- cmd/csi-agent/main.go
- cmd/mount-proxy-client/main.go
- cmd/mount-proxy-server/main.go
- deploy/chart/templates/controller.yaml
- go.mod
- main.go
- pkg/agent/queryserver.go
- pkg/disk/disk.go
- pkg/ens/ens.go
- pkg/metric/disk_stat_collector.go
- pkg/metric/nfs_stat_collector.go
- pkg/options/genericoptions.go
- pkg/pov/pov.go
- pkg/utils/global.go
- pkg/utils/util.go
/kind feature
Besides, use pflag package instead for float32Var.
Fixes #
```release-note
```
```docs
```
> support -kube-api-qps and -kube-api-burst flags, unify all client config

- pkg/mounter/proxy_mounter.go
- pkg/oss/nodeserver.go
- pkg/oss/utils.go
/kind cleanup
mountutils.IsNotMountPoint is deprecated.
IsLikelyNotMountPoint only fails if it is bind mount within the same device. We don't have such case.
Fixes #
```release-note
NONE
```
```docs
```
> oss: use stat to detect mountpoint

- pkg/disk/nodeserver.go
/kind bug
If the umount takes extremely long time and the NodeUnstageVolume RPC times out, kubelet may invoke NodeStageVolume when it retries and we may mistake an unmounting path as a good one. This lock only protects us in one process. But fortunately, when restarting CSI, Kubernetes will wait for the previous process to exit before starting the new one, even if it stucks in uninterruptible syscall (D state). So, we will not have multiple processes on the same node and the lock should be safe enough.
Note that there is still small chance that the previous attach/detach OpenAPI is invoked by the terminated CSI process, but the state returned by DescribeDisks is not updated yet. We should fix this by switch attach/detach to controller.
This is a backport commit. We backport this to …
> [v1.26] disk: avoid concurrent operation on the same disk

- pkg/disk/cloud.go
- pkg/disk/constants.go
- pkg/disk/controllerserver.go
/kind bug
CSI requires us to ensure the snapshot is cut before returning. Implementing this by describe the just created snapshot and ensure its CreationTime is set.
Fixes #
```release-note
We now properly ensure the snapshot is cut before creating the VolumeSnapshotContent
```
```docs
```
> disk/snapshot: wait for cut

- pkg/cloud/metadata/ack_cluster_profile.go
In Private Cloud, cluster profile only has clusterId and resourceGroupId key.
ack-cluster-profile provider should return error to avoid a nil string, and allow the following providers to keep trying retrieve the values.
/kind bug
Fixes #
```release-note
```
```docs
```
> metadata: if value in cluster profile is empty, return error

- pkg/mounter/ossfs.go
Different with `flag`, `pflag` will see a flag like `-socket` as  `-s`.
Use flags in long form to keep compatible with the `pflag`, it still works with the older  mount-proxy(ossfs) version.
/kind bug
Fixes #
```release-note
```
```docs
```
> fix: use long form for flags when create ossfs pod to keep conpatible with pflag

- deploy/chart/templates/fuse.yaml
- pkg/mounter/fuse_pod_manager.go
- pkg/oss/controllerserver.go
/kind cleanup
VolumeAttchment will not be created when the pod scheduled to VK.
For service account not exists, got event like
```
Warning  FailedAttachVolume  2s (x4 over 7s)  attachdetach-controller  AttachVolume.Attach failed for volume "pv-oss" : rpc error: code = Internal desc = failed to create ossfs pod: pods "csi-fuse-ossfs-" is forbidden: error looking up service account ack-csi-fuse/a-fake-sa: serviceaccount "a-fake-sa" not found
``` 
Fixes #
```release-note
```
```docs
```
> remove node check (for vk) and serviceaccount check

- pkg/metric/common.go
- pkg/metric/disk_stat_collector.go
- pkg/metric/nfs_stat_collector.go
- pkg/metric/proc_diskstats.go
- pkg/metric/proc_diskstats_test.go
- pkg/metric/utils.go
- vendor/github.com/prometheus/procfs/blockdevice/stats.go
- vendor/modules.txt
/kind cleanup
/kind feature
This add back I/O hang alert removed by commit 656877777b5dd98a8d8e3c9594cdc1e7b0306d75.
The previous implementation is prone to false positive if an IO is started just before we collect stats.
In this version, we ensure there is no progress for at least 30s before alert.
This patch also switch to prometheus package for parsing /proc/diskstats, and avoids hard codes magic indices everywhere.
Fix the metrics `{read,write}_time_milliseconds_total` to be really milliseconds (they are in seconds before). Also fix the metric help text.
Fix that metrics `{capacity_bytes,inodes}_{available,total,used}` should be gauge instead of counter.
should reduce the number of args, and also pass along PVC UID
just get the device number from mountpoint
Fixes #
The first 4 commits …
> metric: disk hang alert and some cleanup

- deploy/chart/templates/controller.yaml
- deploy/chart/templates/plugin.yaml
- pkg/disk/utils.go
/kind cleanup
#449 seems to want to enable VPC endpoint for the listed 19 regions, but ended up using public endpoint for them and use VPC endpoint for other regions. Now we are sure the listed 19 (actually 18) regions support VPC endpoint, and we have been using VPC endpoint for other regions for years without problem. So this change should be safe.
For the listed regions:
* ap-south-1: already closed
* cn-north-2-gov-1: manually checked `ecs-vpc.cn-north-2-gov-1.aliyuncs.com` is accessable
* All other regions are listed in the official doc: https://help.aliyun.com/zh/ecs/developer-reference/call-api-operations-over-the-internal-network?spm=a2c4g.11186623.0.0.10ce48d1z8j7YM
Now VPC endpoint is available for all regions, we should use them by default so that we don't rely on Internet …
> Access ECS OpenAPI using the VPC endpoint on ECS

- build/csi-agent/Dockerfile
- build/mount-proxy/Dockerfile
- build/multi/Dockerfile.multi
- build/multi/Dockerfile.multi.asi
- go.mod
- pkg/cloud/metadata/ack_cluster_profile.go
- pkg/cloud/metadata/ack_cluster_profile_test.go
- pkg/cloud/metadata/metadata.go
- pkg/cloud/metadata/metadata_test.go
- pkg/disk/controllerserver.go
- pkg/disk/disk.go
- pkg/disk/utils.go
- pkg/disk/utils_test.go
/kind bug
/kind cleanup
Pick the first from the intersection of parameter and AccessibilityRequirements.
Ensure error is returned when parameter and AccessibilityRequirements conflicts, or when unknown topology is specified.
fix possible race in storageClassZonePos, it is now removed. We will respect the order from AccessibilityRequirements, falling back to random.
Replaces #1375 
```release-note
We now returns error when zoneID in parameter and AccessibilityRequirements conflicts, or when unknown topology is specified.
```
```docs
```
> disk: refactor determine ZoneID

- pkg/mounter/oss/ossfs.go
- pkg/mounter/oss/ossfs2.go
- pkg/mounter/oss/ossfs2_test.go
- pkg/mounter/oss/ossfs_test.go
/kind bug
use /dev/stdout as default log_dir for ossfs 2.0.
Fixes #
```release-note
```
```docs
```
> ossfs2: set default logdir to /dev/stdout

- pkg/nas/cloud/utils.go
- pkg/nas/cloud/utils_test.go
/kind bug
In private cloud environments, NAS service domain names do not follow the `nas.aliyuncs.com` format. This leads to the file system type being incorrectly determined in these private clouds.
To resolve this for private cloud use cases, this patch makes 'standard' the default NAS file system type.
Fixes #
```release-note
none
```
```docs
```
/cc @AlbeeSo
> nas: make 'standard' the default NAS file system type

- deploy/chart/templates/controller.yaml
- deploy/chart/values.yaml
/kind cleanup
Promote VolumeAttributesClass feature gate to beta
Promoted the feature gate `HonorPVReclaimPolicy` to GA
Enable json logging format
Fixes #
```release-note
Promote VolumeAttributesClass feature gate to beta
Promoted the feature gate `HonorPVReclaimPolicy` to GA
external-provisioner supports json logging format
Only allow whitelisted parameters from PVC annotation
```
```docs
```
> bump external-provisioner to v5.3.0

- pkg/disk/category.go
- pkg/disk/cloud_test.go
What type of PR is this?
/kind feature
What this PR does / why we need it:
In some financial cloud scenarios, we need support some special disk category as cloud_essd_xc0 and cloud_essd_xc1
Which issue(s) this PR fixes:
Fixes #
Special notes for your reviewer:
Does this PR introduce a user-facing change?
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
> feat:support cloud essd with new disk type as xc0 and xc1

- pkg/cnfs/v1beta1/types.go
- pkg/nas/nodeserver.go
- pkg/nas/nodeserver_test.go
- pkg/utils/util.go
/kind feature
Fixes #
```release-note
```
```docs
```
> feat(nas): automatic CNFS switching when mounting NAS volumes

- pkg/disk/category.go
- pkg/disk/cloud.go
/kind feature
In some cases, we cannot detach a disk from ECS, maybe because of
malfunctioning guest OS, or communication issue between control and data plane.
When this happens, we can use force attach to escape to another instance, in
order to recover workload.  The old instance will see I/O error if detach
failed, and the detach will be retried by ECS.
Force attach is currently only possible for regional ESSD, when old and new
instances are in different zone. These restrictions may be lifted in the
future.
For this to work, we rely on KCM to initiate attaching after the first
detaching failed. i.e. Failed detaching will not block next attaching.
Fixes #
```release-note
Use force attach when we cannot detach the disk.
```
```docs
```
> disk: try force attach if the same disk is already detaching

- pkg/mounter/oss/ossfs.go
- pkg/mounter/oss/ossfs2.go
- pkg/mounter/oss/ossfs2_test.go
- pkg/mounter/oss/ossfs_test.go
/kind feature
https://help.aliyun.com/zh/oss/developer-reference/listobjects#section-t6d-ovx-jse
As the document of OSS, it's recommended to use listObjectsV2 by default.
Fixes #
```release-note
```
```docs
```
> ossfs 1.0: add default option: listobjectsv2

- pkg/common/nodeserver.go
- pkg/metric/volume_stat_collector.go
/kind cleanup
Restarting kubelet will also re-publish all volumes. We should exclude them.
Also only count success attach.
Add 0 at init so we will not miss the first attach with promQL rate().
Fixes #
```release-note
NONE
```
```docs
```
> metric: only count pending pod for attachment time

- pkg/disk/cloud.go
- pkg/disk/controllerserver.go
- pkg/disk/nodeserver.go
/kind bug
We use disk.InstanceId for DetachDisk request, but it is empty for multi-attach disk. But no matter how ADControllerEnable feature-gate is set, we should detach the disk from controller. So fix this by explicitly skip detaching multi-attach disk from node.
Before 400101041 ("disk: replace all wait logic with waiter"), we also use disk.InstanceId to check whether the disk is attached, which will fail for multi-attach disk. That is replaced by the more robust `IsInstanceAttached`, which recognizes multi-attach disk, but creates the inconsistency.
Fixes: 4001010418f96505f14b7170057b93f3ebf1491b
```release-note
Fix multi-attach disk detaching from node
```
```docs
```
> disk: fix multi-attach disk detaching from node.

- pkg/utils/cgroup/pod.go
- pkg/utils/cgroup/pod_test.go
/kind feature
Fixes #
```release-note
support for kubelet --cgroup-driver=cgroupfs
```
```docs
```
> utils/cgroup: support for cgroupFS driver

- pkg/disk/csi_agent.go
- pkg/mounter/cmd_mounter.go
- pkg/mounter/proxy/server/ossfs/driver.go
- pkg/mounter/proxy/server/ossfs2/driver.go
- pkg/mounter/utils/utils.go
- pkg/nas/mounter.go
- pkg/nas/nodeserver.go
- pkg/oss/csi_agent.go
- pkg/oss/nodeserver.go
/kind feature
1. Enable disk volume stats by default.
2. Support ossfs 2.0 in OssCmdMounter.
3. Support mount NAS using EFCClient with `useClient` field.
```release-note
```
```docs
```
> csi-agent: cmd mounter support ossfs 2.0 & add volume stats capability to disk driver

- pkg/disk/cloud.go
- pkg/disk/device_manager.go
- pkg/disk/device_manager_test.go
- pkg/disk/nodeserver.go
- pkg/disk/utils.go
/kind bug
Make attachDisk returns the root device, then adapt partition in a unified place, and only for mount volumes. Allow block volume should not be affected by partitions.
Fixes #
```release-note
Block volume is allowed to contain partition table now.
```
```docs
```
> disk: only adapt partition for mount volumes
