kubernetes-sigs/alibaba-cloud-csi-driver

README-zh_CN.md, README.md
readme add CN Language support
=> add zh readme

pkg/disk/controllerserver.go, pkg/disk/nodeserver.go
=> move detach to nodeserver

deploy/all/csi-plugin.yaml, deploy/all/csi-provisioner.yaml, pkg/disk/controllerserver.go, pkg/disk/utils.go
=> update disk plugin topology

build/build-all.sh, build/build-disk.sh, build/build-lvm.sh, build/build-nas.sh, build/build-oss.sh, pkg/disk/nodeserver.go, pkg/utils/util.go
=> update ebs umount

pkg/disk/controllerserver.go, vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ecs/create_disk.go
support byok encryption for disk type volume
=> support byok encryption for disk type volume

pkg/disk/nodeserver.go
Isformat can't check disk format correctly. Use SafeFormatAndMount.FormatAndMount() directly
=> remove isformat for disk plugin

deploy/ack/csi-provisioner.yaml, pkg/disk/controllerserver.go, vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ecs/create_disk.go
support essd performance level
=> support essd performance level

README.md, deploy/nas/nas-provisioner.yaml, docs/nas-dynamic.md, docs/nas.md, examples/nas/dynamic/pvc.yaml, examples/nas/dynamic/sc-filesystem.yaml, examples/nas/dynamic/sc-subpath.yaml, pkg/nas/controllerserver.go, pkg/nas/nas.go, pkg/nas/nodeserver.go, pkg/nas/utils.go
=> support provision nfs volume

README.md, build/build-all.sh, build/build-cpfs.sh, build/build-disk.sh, build/build-lvm.sh, build/build-nas.sh, build/build-oss.sh, docs/oss-upgrade.md, go.mod, main.go, pkg/cpfs/cpfs.go, pkg/cpfs/nodeserver.go, pkg/cpfs/utils.go, pkg/disk/nodeserver.go, pkg/disk/utils.go, pkg/lvm/nodeserver.go, pkg/nas/controllerserver.go, pkg/nas/nas.go, pkg/nas/nodeserver.go, pkg/nas/utils.go, pkg/oss/nodeserver.go
refine import path from AliyunContainerService to kubernetes-sigs
=> refine import path from AliyunContainerService to kubernetes-sigs

deploy/oss/oss-plugin.yaml, docs/oss.md
fix [issue#75](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/issues/75)
=> add oss plugin deploy yaml files and update docs

docs/disk-resizer.md, docs/disk-snapshot.md, docs/disk.md
fix issue[#77](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/issues/77)
=> update disk releated help docs

build/cpfs/Dockerfile, build/cpfs/entrypoint.sh, deploy/cpfs/cpfs-plugin.yaml, examples/cpfs/deploy.yaml, main.go, pkg/cpfs/nodeserver.go, pkg/cpfs/utils.go
=> update cpfs driver

build/build-disk.sh, pkg/disk/controllerserver.go
fix issue[#44](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/issues/44)
=> support resourceGroupId args when create a volume

pkg/disk/controllerserver.go, pkg/disk/nodeserver.go
handle the empty reponse case when describe disk
=> handle the empty reponse case when describe disk

pkg/disk/controllerserver.go, pkg/disk/nodeserver.go, pkg/disk/utils.go, pkg/lvm/controllerserver.go, pkg/lvm/nodeserver.go
=> ineffassign and misspell fix

docs/disk-snapshot.md, pkg/cpfs/nodeserver.go, pkg/cpfs/utils.go, pkg/disk/disk.go, pkg/disk/utils.go, pkg/lvm/identityserver.go, pkg/lvm/lvm.go, pkg/nas/nas.go, pkg/nas/utils.go, pkg/oss/nodeserver.go, pkg/oss/oss.go, pkg/utils/util.go
=> fix golint and doc refine

pkg/nas/controllerserver.go
fix issue [#97](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/issues/97)
=> modify subpath mount dir

deploy/nas/nas-plugin.yaml, deploy/nas/nas-provisioner.yaml, docs/nas-dynamic.md, examples/nas/dynamic/sc-filesystem.yaml
fix issue [#99](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/issues/99)
=> update nas docs

pkg/nas/controllerserver.go
fix issue [#103](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/issues/103)
=> add option to support delele policy in  filesysyem type nas volume

deploy/nas/nas-plugin.yaml, deploy/nas/nas-provisioner.yaml, docs/nas-dynamic.md, examples/nas/dynamic/sc-filesystem.yaml
fix issue [#106](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/issues/106)
=> update nas deploy docs

examples/nas/dynamic/sc-filesystem.yaml, examples/nas/dynamic/sc-subpath.yaml, pkg/nas/controllerserver.go
fix issue [#108](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/issues/108)
=> update nas delete volume policy

deploy/nas/nas-plugin.yaml, deploy/nas/nas-provisioner.yaml
fix issue [#108](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/issues/108)
=> update nas plugin image tag

build/oss/csiplugin-connector.go, main.go, pkg/cpfs/controllerserver.go, pkg/cpfs/cpfs.go, pkg/cpfs/nodeserver.go, pkg/cpfs/utils.go, pkg/disk/controllerserver.go, pkg/disk/disk.go, pkg/disk/nodeserver.go, pkg/disk/utils.go, pkg/lvm/controllerserver.go, pkg/lvm/lvm.go, pkg/lvm/nodeserver.go, pkg/lvm/utils.go, pkg/nas/controllerserver.go, pkg/nas/nas.go, pkg/nas/nodeserver.go, pkg/nas/utils.go, pkg/oss/nodeserver.go, pkg/oss/oss.go, pkg/oss/utils.go, pkg/utils/mounter.go, pkg/utils/util.go
fix issue [#112 ](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/issues/112)
=> fix code quality issues

main.go, pkg/cpfs/controllerserver.go, pkg/cpfs/cpfs.go, pkg/disk/controllerserver.go, pkg/disk/nodeserver.go, pkg/disk/utils.go, pkg/lvm/nodeserver.go, pkg/lvm/utils.go, pkg/nas/controllerserver.go, pkg/nas/nas.go, pkg/nas/nodeserver.go, pkg/nas/utils.go, pkg/oss/nodeserver.go, pkg/oss/utils.go, pkg/utils/util.go
fix issue [#112 ](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/issues/112)
=> update to enhance code quality

OWNERS
=> request reviewer

Makefile, build/oss/csiplugin-connector.go, hack/check-format.sh, hack/check-golint.sh, hack/check-govet.sh, hack/check-unittest.sh, hack/run-e2e-test.sh, hack/update-gofmt.sh, main.go, pkg/cpfs/controllerserver.go, pkg/cpfs/cpfs.go, pkg/cpfs/nodeserver.go, pkg/disk/controllerserver.go, pkg/disk/disk.go, pkg/lvm/controllerserver.go, pkg/lvm/identityserver.go, pkg/lvm/lvm.go, pkg/lvm/utils.go, pkg/nas/nas.go, pkg/nas/nodeserver.go, pkg/oss/nodeserver.go, pkg/oss/nodeserver_test.go, pkg/oss/oss.go
fix issue [#122 ](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/issues/122)
=> code qualit checking scripts

go.mod, pkg/disk/controllerserver.go, pkg/disk/nodeserver.go, pkg/disk/utils.go, vendor/github.com/sirupsen/logrus/.gitignore, vendor/github.com/sirupsen/logrus/.travis.yml, vendor/github.com/sirupsen/logrus/CHANGELOG.md, vendor/github.com/sirupsen/logrus/LICENSE, vendor/github.com/sirupsen/logrus/README.md, vendor/github.com/sirupsen/logrus/alt_exit.go, vendor/github.com/sirupsen/logrus/appveyor.yml, vendor/github.com/sirupsen/logrus/doc.go, vendor/github.com/sirupsen/logrus/entry.go, vendor/github.com/sirupsen/logrus/exported.go, vendor/github.com/sirupsen/logrus/formatter.go, vendor/github.com/sirupsen/logrus/go.mod, vendor/github.com/sirupsen/logrus/go.sum, vendor/github.com/sirupsen/logrus/hooks.go, vendor/github.com/sirupsen/logrus/json_formatter.go, vendor/github.com/sirupsen/logrus/logger.go, vendor/github.com/sirupsen/logrus/logrus.go, vendor/github.com/sirupsen/logrus/terminal_check_appengine.go, vendor/github.com/sirupsen/logrus/terminal_check_bsd.go, vendor/github.com/sirupsen/logrus/terminal_check_no_terminal.go, vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go, vendor/github.com/sirupsen/logrus/terminal_check_solaris.go, vendor/github.com/sirupsen/logrus/terminal_check_unix.go, vendor/github.com/sirupsen/logrus/terminal_check_windows.go, vendor/github.com/sirupsen/logrus/text_formatter.go, vendor/github.com/sirupsen/logrus/writer.go
=> update disk sc avaiable logic

examples/disk/topology/storageclass.yaml, examples/nas/pv.yaml, pkg/nas/controllerserver.go, pkg/nas/utils.go, pkg/oss/nodeserver.go
update jisu nas check:
Extreme nas url always contains: "extreme.nas.aliyuncs.com", Like:
```
012ee3cb-vmb2.cn-beijing.extreme.nas.aliyuncs.com:/share
```
Create SubPath for nas should under /share path;
=> update jisu nas check

pkg/disk/controllerserver.go
=> fix golint issue

CHANGELOG-v1.0.x.md, deploy/ack/csi-plugin.yaml, deploy/ack/csi-provisioner.yaml
=> v1.0.1 release notes

pkg/disk/utils.go
support unitized endpoint for disk volume.
=> support unitized endpoint

pkg/nas/utils.go
=> support nas unitized endpoint

go.mod, pkg/disk/controllerserver.go, pkg/disk/nodeserver.go, pkg/disk/utils.go
=> support disk mkfsoptions

deploy/rbac.yaml
=> update rbac namespaces

deploy/lvm/lvm-provisioner.yaml, examples/lvm/topology/storageclass.yaml, pkg/lvm/controllerserver.go, pkg/lvm/identityserver.go, pkg/lvm/nodeserver.go
=> lvm support topology

deploy/ack/csi-provisioner.yaml, deploy/cpfs/cpfs-provisioner.yaml, deploy/disk/disk-provisioner.yaml, deploy/disk/resizer/csi-resizer.yaml, deploy/disk/snapshot/csi-external-snapshot.yaml, deploy/lvm/lvm-provisioner.yaml, deploy/lvm/resizer/csi-resizer.yaml, deploy/nas/nas-provisioner.yaml
=> update provisioner version

docs/oss.md, examples/oss/pv.yaml, pkg/oss/nodeserver.go, pkg/oss/nodeserver_test.go
=> support oss subpath

deploy/oss/oss-plugin.yaml, docs/oss.md
=> update oss image

build/oss/csiplugin-connector.go, build/oss/csiplugin-connector_test.go, pkg/oss/nodeserver.go
=> check illegal oss command

examples/nas/dynamic/sc-subpath.yaml, pkg/disk/nodeserver.go, pkg/nas/controllerserver.go, pkg/nas/nodeserver.go, pkg/nas/utils.go, pkg/utils/util.go
=> nas mntOptions update

deploy/ack/csi-plugin.yaml, deploy/ack/csi-provisioner.yaml, deploy/disk/block/disk-plugin.yaml, deploy/disk/disk-plugin.yaml, deploy/disk/disk-provisioner.yaml, deploy/disk/resizer/csi-resizer.yaml, deploy/lvm/lvm-plugin.yaml, deploy/nas/nas-plugin.yaml, deploy/nas/nas-provisioner.yaml, deploy/oss/oss-plugin.yaml
=> update plugin images

build/build-mem.sh, build/mem/Dockerfile, deploy/mem/mem-plugin.yaml, deploy/mem/mem-provisioner.yaml, docs/memory.md, examples/mem/deploy.yaml, examples/mem/pv.yaml, examples/mem/pvc.yaml, examples/mem/storageclass.yaml, main.go, pkg/mem/controllerserver.go, pkg/mem/identityserver.go, pkg/mem/mem.go, pkg/mem/nodeserver.go, pkg/mem/utils.go
=> support memory type volume

docs/memory.md
correct the location of examples of memory volumes
=> correct the location of examples of memory volumes

pkg/oss/nodeserver.go, pkg/oss/oss.go, pkg/oss/utils.go
fix issue [#170 ](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/issues/170)
=> support UseSharedPath when creating oss volume

build/oss/Dockerfile, build/oss/entrypoint.sh
fix issue [#176 ](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/issues/176)
=> upgrade ossfs version

test/disk/disk-aware.sh, test/disk/disk-dynamic.sh, test/nas/nas-static.sh, test/oss/oss-static.sh
Signed-off-by: Yuan Sun <yile.sy@alibaba-inc.com>
=> add bucket for oss/oss-static.sh

pkg/disk/nodeserver.go, pkg/disk/utils.go
=> support disk virtio link

build/all/entrypoint.sh, deploy/ack/csi-plugin.yaml, deploy/ack/csi-provisioner.yaml
fix issue [#182 ](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/issues/182)
=> update to match kubernetes v1.16

build/all/Dockerfile, build/all/entrypoint.sh, deploy/ack/csi-provisioner.yaml, pkg/disk/cloud.go, pkg/disk/controllerserver.go, pkg/disk/utils.go
=> update detach strategy

pkg/oss/nodeserver.go
=> path bugfix

deploy/ack/csi-plugin.yaml, deploy/ack/csi-provisioner.yaml
=> update image version

deploy/ack/csi-plugin.yaml, deploy/ack/csi-provisioner.yaml, pkg/oss/nodeserver.go
=> V1.0.3 update default osspath

pkg/disk/utils.go, pkg/nas/utils.go
V1.0.3 internal endpoint support
=> V1.0.3 internal endpoint

deploy/ack/csi-provisioner.yaml, pkg/nas/controllerserver.go
=> update nas template

pkg/disk/utils.go
=> update mount check

pkg/oss/nodeserver.go
=> add oss log

deploy/agent/csi-plugin.yaml, main.go, pkg/agent/agent.go, pkg/agent/queryserver.go, pkg/disk/nodeserver.go, pkg/nas/nas.go, pkg/nas/nodeserver.go, pkg/utils/util.go
=> V1.0.3 support kata

deploy/agent/csi-plugin.yaml, pkg/disk/disk.go, pkg/disk/nodeserver.go, pkg/nas/nas.go, pkg/nas/nodeserver.go, pkg/utils/util.go
=> support kata runtime

pkg/agent/agent.go, pkg/agent/queryserver.go, pkg/disk/nodeserver.go, pkg/nas/nodeserver.go, pkg/utils/util.go
=> change config file

pkg/disk/controllerserver.go, pkg/disk/disk.go, pkg/disk/nodeserver.go
=> V1.0.3 disk notdetach

pkg/disk/disk.go, pkg/disk/utils.go, pkg/local/utils.go, pkg/lvm/utils.go, pkg/nas/nas.go, pkg/nas/utils.go, pkg/utils/auth.go, pkg/utils/util.go
=> support secret

pkg/disk/disk.go, pkg/local/lib/commands/commands.go, pkg/local/lib/parser/parser.go, pkg/local/lib/proto/lvm.pb.go, pkg/local/nodeserver.go, pkg/local/server/routers.go, pkg/local/utils.go, pkg/nas/nas.go
=> update lvm striping

deploy/local/plugin.yaml, examples/local/storageclass.yaml
=> update lvm template

build/ack/Dockerfile, deploy/disk/bdf/csi-plugin.yaml, deploy/disk/bdf/csi-provisioner.yaml, go.mod, go.sum, pkg/disk/bdf.go, pkg/disk/cloud.go, pkg/disk/controllerserver.go, pkg/disk/disk.go, pkg/disk/nodeserver.go, pkg/disk/utils.go, vendor/github.com/pkg/errors/.gitignore, vendor/github.com/pkg/errors/.travis.yml, vendor/github.com/pkg/errors/LICENSE, vendor/github.com/pkg/errors/README.md, vendor/github.com/pkg/errors/appveyor.yml, vendor/github.com/pkg/errors/errors.go, vendor/github.com/pkg/errors/stack.go, vendor/modules.txt
=> V1.0.4 support bdf

deploy/local/provisioner.yaml, pkg/local/lib/commands/commands.go, pkg/local/nodeserver.go, pkg/local/server/routers.go
=> support lvm resize

pkg/oss/nodeserver.go, pkg/oss/utils.go
CSI support STS authentication
=> CSI support STS authentication

pkg/cpfs/controllerserver.go, pkg/disk/nodeserver.go, pkg/nas/controllerserver.go, pkg/utils/util.go
=> update disk publish

pkg/disk/cloud.go, pkg/disk/controllerserver.go, pkg/disk/nodeserver.go, pkg/oss/nodeserver.go
=> update disk availible

build/ack/entrypoint.sh, pkg/disk/cloud.go, pkg/disk/nodeserver.go, pkg/disk/utils.go
=> add disk uuid

pkg/local/adapter/scheduler.go, pkg/local/client/http.go, pkg/local/controllerserver.go, pkg/local/controllerutils.go
=> support local scheduler

pkg/disk/nodeserver.go, pkg/nas/nodeserver.go, pkg/utils/util.go
=> update runtime logical

deploy/ack/upgrade/upgrade_csi-plugin.sh, deploy/ack/upgrade/upgrade_csi-provisioner.sh, pkg/disk/disk.go
support RUNTIME env for runc/runc
=> support RUNTIME env for runc/runc

pkg/disk/disk.go, pkg/disk/nodeserver.go
=> add disk detach env

pkg/disk/cloud.go, pkg/disk/controllerserver.go
=> support disk snapshot/restore

pkg/disk/nodeserver.go
=> update disk block expand

pkg/disk/utils.go
=> update bdf serial device

deploy/disk/snapshot/crd.yaml, deploy/disk/snapshot/csi-snapshotter.yaml, docs/disk-restore.md, docs/disk-snapshot.md, examples/disk/snapshot-restore/pvc.yaml, examples/disk/snapshot-restore/sts-restore.yaml, examples/disk/snapshot-restore/sts.yaml, examples/disk/snapshot/snapshot.yaml, examples/disk/snapshot/snapshotclass.yaml, pkg/disk/controllerserver.go
support volumesnapshot beta version
=> V1.0.5 snapshot beta

pkg/disk/nodeserver.go
=> fix block double mount

pkg/local/controllerserver.go, pkg/local/nodeserver.go, pkg/local/nodeutils.go, pkg/local/utils.go, pkg/lvm/nodeserver.go
=> update local logs

main.go, pkg/om/blockvolume.go, pkg/om/om.go, pkg/om/orphaned.go, pkg/om/utils.go
=> add storage issue logical

deploy/ack/csi-plugin.yaml, deploy/ack/csi-provisioner.yaml, deploy/ack/upgrade/upgrade_csi-plugin.sh, deploy/ack/upgrade/upgrade_csi-provisioner.sh
=> Release v1.0.6

main.go, pkg/local/adapter/scheduler.go, pkg/local/nodeserver.go, pkg/local/nodeutils.go
=> update local volume

pkg/local/controllerserver.go, pkg/local/utils.go
=> fix lvm remove error

pkg/local/controllerserver.go
fix remove mountpoint volume exception when the pv's nodeaffinity is nil.
=> fix MountPoint volume remove error

pkg/disk/cloud.go, pkg/disk/nodeserver.go, pkg/disk/utils.go
=> remove uuid logical

pkg/disk/bdf.go
=> update vf check

pkg/disk/cloud.go, pkg/disk/controllerserver.go
=> Add find ecsSnapshot by id

pkg/nas/controllerserver.go, pkg/nas/utils.go
=> fix nas dup mount issue

deploy/ack/csi-plugin.yaml, deploy/ack/csi-provisioner.yaml, deploy/ack/upgrade/upgrade_csi-plugin.sh, deploy/ack/upgrade/upgrade_csi-provisioner.sh, deploy/mem/mem-plugin.yaml, deploy/mem/mem-provisioner.yaml
=> release v1.0.7

pkg/disk/disk.go, pkg/disk/utils.go
=> Use REGION_ID environment variable by default when newEcsClient

build/build-all.sh, build/build-disk.sh, build/build-nas.sh
Change the build directory of the csi-driver to adapt git fork
=> Update build all scripts

Makefile
Add build function to makefile
=> Add build function to makefile

pkg/disk/disk.go, pkg/nas/nas.go
=> support kata2.0

pkg/disk/utils.go
Support upgrade from k8s 1.16 to 1.18
=> Support upgrade from k8s 1.16 to 1.18

pkg/disk/nodeserver.go, pkg/disk/utils.go
Add block device volumeid check
=> Add block device volumeid check

build/build-all.sh, pkg/disk/controllerserver.go, pkg/disk/nodeserver.go, pkg/nas/controllerserver.go, pkg/utils/error_types.go, pkg/utils/error_types_test.go
Add suggestion to openapi error
=> Add suggestion to openapi error

pkg/metric/diskstat_collector.go
fix getMetric no such file or directory
=> fix getMetric no such file or directory

deploy/rbac.yaml
=> update rbac spec

pkg/nas/utils.go
=> fix nfs remount error

pkg/disk/utils.go
=> fix ecsendpoint format bug

pkg/metric/pfsstat_collector.go, pkg/metric/utils.go
=> fix deadlock bug

build/ack/Dockerfile, pkg/metric/common.go, pkg/metric/diskstat_collector.go, pkg/metric/pfsstat_collector.go
fix vol_data_json is invalid bug
=> fix vol_data_json is invalid bug

pkg/metric/common.go, pkg/metric/pfsstat_collector.go
Fix the bug that the volumeMount print log cannot be found
=> Fix the bug that the volumeMount print log cannot be found

pkg/disk/utils.go, pkg/disk/utils_test.go
=> Remove essd from available

pkg/nas/controllerserver.go, pkg/nas/nas.go, pkg/nas/utils.go
=> nas subpath support quota

deploy/ack/csi-plugin-dedicate.yaml, deploy/ack/csi-plugin-managed.yaml, deploy/ack/csi-provisioner-dedicate.yaml, deploy/ack/csi-provisioner-managed.yaml
=> security-reinforcement

pkg/nas/nodeserver.go
fix loopsetup umount but nas not umount bug
=> fix loopsetup umount but nas not umount bug

build/ack/Dockerfile
upgrade centos image to 7.9.2009
=> upgrade centos image to 7.9.2009

deploy/rbac.yaml, pkg/disk/controllerserver.go, pkg/disk/disk.go, pkg/disk/nodeserver.go, pkg/disk/utils.go
Have to add Node update authority to alicloud-csi-plugin
=> Disk resource collector

pkg/metric/mountstats.go, pkg/metric/nfsstats_collector.go
use prometheus library parse mountstats
=> use prometheus library parse mountstats

pkg/disk/nodeserver.go, pkg/disk/utils.go
=> Add disk expand context for resizefs

pkg/nas/controllerserver.go
sc delete parameter volumeCapacity
=> sc delete parameter volumeCapacity

build/ack/entrypoint.sh
Modify the logic of judging alinux3
=> Modify the logic of judging alinux3

pkg/cnfs/v1alpha1/types.go
=> support-TrashCanReservedDays

pkg/cnfs/v1beta1/base.go, pkg/cnfs/v1beta1/types.go, pkg/nas/controllerserver.go, pkg/nas/nodeserver.go, pkg/nas/utils.go
modify-cnfs-version-to-v1beta1
=> modify-cnfs-version-to-v1beta1

pkg/cnfs/v1beta1/base.go, pkg/cnfs/v1beta1/types.go, pkg/nas/controllerserver.go, pkg/nas/nodeserver.go, pkg/nas/utils.go
add TrashCanReservedDays field and modify cnfs version to v1beta1
=> add TrashCanReservedDays field and modify cnfs version to v1beta1

build/ack/Dockerfile, build/ack/entrypoint.sh
=> fix ossfs dont sync data bug

build/build-all.sh, pkg/cpfs/controllerserver.go, pkg/nas/controllerserver.go
=> Fix driver forced convert type panic

deploy/ack/csi-provisioner.yaml, deploy/cpfs/cpfs-provisioner.yaml, deploy/disk/disk-provisioner.yaml, deploy/local/provisioner.yaml, deploy/lvm/lvm-provisioner.yaml, deploy/mem/mem-provisioner.yaml, deploy/nas/nas-provisioner.yaml
=> Support external provisioner v3.0.0

build/cpfs/entrypoint.sh, build/multi/Dockerfile.multi, build/multi/amd64-entrypoint.sh, pkg/cpfs/nodeserver.go, pkg/nas/nodeserver.go
fix cpfs version, fix ossfs sync data bug and add cpfs validate
=> fix cpfs version, fix ossfs sync data bug and add cpfs validate

pkg/metric/http.go
=> delete metric nas error log

pkg/disk/nodeserver.go, pkg/disk/utils.go
=> Fix snapshot recover disks mount

build/cpfs/entrypoint.sh
modify cpfs version to 2.10.8-205a
=> modify cpfs version to 2.10.8-205a

pkg/cnfs/v1beta1/base.go, pkg/metric/utils.go, pkg/nas/controllerserver.go, pkg/nas/nodeserver.go, pkg/nas/utils.go
When deleting a subdirectory, the quota limit will be cancelled at the same time.
=>  When deleting a subdirectory, the quota limit will be cancelled at the same time.

pkg/nas/controllerserver.go, pkg/nas/utils.go
fix only capacity and hibrid nas support quota bug.
=> fix only capacity and hibrid nas support quota bug

deploy/ack/csi-plugin.yaml, deploy/ack/csi-provisioner.yaml
Fixes #
```release-note
update new csi templates.
```
```docs
```
=> update v1.1.5 templates

deploy/ack/csi-plugin.yaml, deploy/ack/csi-provisioner.yaml, deploy/disk/disk-plugin.yaml, deploy/disk/disk-provisioner.yaml
update deploy yaml of csi-provisioner & csi-plugin to support k8s 1.22
None
```release-note
```
=> Update default yaml image version to support k8s1.22

pkg/disk/nodeserver.go, pkg/disk/utils.go
Fixes #
```release-note
support nvme volume expand.
```
```docs
```
=> support nvme expand

go.mod, go.sum, main.go, pkg/agent/queryserver.go, pkg/dbfs/dbfs.go, pkg/dbfs/nodeserver.go, pkg/disk/disk.go, pkg/disk/nodeserver.go, pkg/local/generator/pvcHandler.go, pkg/local/local.go, pkg/local/nodeserver.go, pkg/lvm/nodeserver.go, pkg/mem/mem.go, pkg/mem/nodeserver.go, pkg/metric/diskstat_collector.go, pkg/metric/nfsstats_collector.go, pkg/metric/pfsstat_collector.go, pkg/nas/nas.go, pkg/nas/nodeserver.go, pkg/options/genericoptions.go, pkg/utils/util.go
/kind feature
We need a way to run the plugin controller out side of k8s cluster
Fixes #
```release-note
```
```docs
```
=> support kubeconfig args

build/ack/Dockerfile, build/ack/entrypoint.sh, pkg/metric/diskstat_collector.go
update ossfs version to 1.86.5 and fix iohang bug
=> update ossfs version to 1.86.5 and fix iohang bug

build/multi/Dockerfile.multi, build/multi/amd64-entrypoint.sh
=> update ossfs to 1.86.5

pkg/oss/nodeserver.go, pkg/utils/auth.go, pkg/utils/util.go
Fixes #
```release-note
```
```docs
```
=> update auth logs

pkg/local/capacity.go
Fixes #
```release-note
```
```docs
```
=> update storage capacity tag

pkg/disk/controllerserver.go, pkg/disk/utils.go, pkg/disk/utils_test.go, test/channel.go
Fixes #
```release-note
```
```docs
```
=> create disk type by order

pkg/disk/utils.go
Fixes #
```release-note
```
```docs
```
=> update disktype label

pkg/disk/controllerserver.go, pkg/disk/utils.go
Fixes #
```release-note
```
```docs
```
=> static volume support snapshot

hack/check-golint.sh, pkg/utils/util.go
Fixes #
```release-note
```
```docs
```
=> local volume cache NodeAddr

pkg/disk/disk.go, pkg/local/controllerserver.go, pkg/local/local.go, pkg/local/nodeserver.go, pkg/local/secret.go, pkg/nas/nas.go
/kind feature
Support qps env setting for kubeapi reqeust
Fixes #
```release-note
```
```docs
```
=> Add kubecli qps setting for csi

build/multi/Dockerfile.multi
Fixes #
```release-note
```
```docs
```
=> Support growpath in base images

deploy/dbfs/csi-plugin.yaml, deploy/dbfs/csi-provisioner.yaml, pkg/dbfs/nodeserver.go, pkg/dbfs/utils.go
/kind bug
Support new DBFS type storage on k8s
To support new type of dbfs driver path
None
=> Change find dbfs mount path way

deploy/ack/csi-plugin.yaml, pkg/disk/nodeserver.go
Fixes #
```release-note
```
```docs
```
=> Add liveness to ndoe registrar & fix nodestage return err

pkg/local/capacity.go, pkg/local/controllerserver.go, pkg/local/controllerutils.go, pkg/local/nodeutils.go
Fixes #
```release-note
```
```docs
```
=> support local device volume

pkg/dbfs/utils.go
Fixes #
```release-note
```
```docs
```
=> support dbfs endpoint

build/lib/amd64-entrypoint.sh, pkg/nas/nas.go
[modify csi directory to multi_data directory](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/commit/6a848b53628a11d02cba9c87dd968939f6aec989)
=> modify csi directory to multi_data directory

build/amd/Dockerfile, build/lib/amd64-entrypoint.sh
Fixes #
```release-note
```
```docs
```
=> support cpfs nfs

pkg/local/controllerserver.go, pkg/local/controllerutils.go, pkg/local/nodeutils.go
Fixes #
```release-note
```
```docs
```
=> fix local device lower key

build/multi/Dockerfile.multi, pkg/dbfs/nodeserver.go, pkg/dbfs/utils.go, pkg/disk/controllerserver.go
/kind feature
1. Support dbfs set mount device count for per node according to ecs instance type
2. Change build lib dir
3. Support clientToken for create disk 
None
None
=> Support dbfs node max volume config

pkg/nas/nodeserver.go
Fixes #
```release-note
```
```docs
```
=> nas skip mount mode

build/multi/Dockerfile.multi
=> go build use vendor

pkg/local/nodeutils.go
Fixes #
```release-note
```
```docs
```
=> fix local device remount

pkg/dbfs/dbfs.go
/kind bug
Support vpc domain for dbfs
```release-note
```
```docs
```
=> Support dbfs vpc domain

pkg/disk/utils.go
/kind feature
add node support disk labels for special region
Fixes #
```release-note
```
```docs
```
=> Support oxs node instance label & zoneid label

build/lib/arm64-entrypoint.sh
Fixes #
```release-note
```
```docs
```
=> Fix fuse devel install

pkg/disk/controllerserver.go
Fixes #
```release-note
```
```docs
```
=> Fix create disk client token elements

pkg/disk/bdf.go
modify print log diskResponse to instanceResponse
=> modify print log diskResponse to instanceResponse

pkg/local/capacity.go
/kind improve
Remove http access during csidriver starting
Fixes None
```release-note
```
```docs
```
=> Disable global var access to metadata server

pkg/disk/nodeserver.go, pkg/utils/util.go
Fixes #
```release-note
```
```docs
```
=> fix rund remount

build/lib/arm64-entrypoint.sh
modify arm64 /bin/csiplugin-connector to /csi/csiplugin-connector
=> modify arm64 /bin/csiplugin-connector to /csi/csiplugin-connector

pkg/nas/nas.go
modify delete eac and alinas-utils before install
=> modify delete eac and alinas-utils before install

build/amd/Dockerfile, build/lib/amd64-entrypoint.sh, build/multi/Dockerfile.multi, pkg/dadi/dadi.go, pkg/metric/alinas_stat_collector.go, pkg/nas/nas.go
modify parse eac metric uuid:server format
=> modify parse eac metric uuid:server format

build/lib/amd64-entrypoint.sh
=> fix shell spaces bug

pkg/disk/nodeserver.go, pkg/nas/nodeserver.go
Signed-off-by: LetFu <letfu@outlook.com>
/kind bug
This should be a typo.
Fixes #
```release-note
Changed some of the log text in NodePublishVolume
```
```docs
```
=> fix a typo in the log of NodePublishVolume

pkg/oss/nodeserver.go, pkg/oss/oss.go
mutex saveOssfsCredential and uniqOssfsCredential Function
=> mutex saveOssfsCredential and uniqOssfsCredential

build/multi-private/Dockerfile.multi, pkg/disk/utils.go
/kind bug
Enable private image build & add logs
Fixes #
```release-note
```
```docs
```
=> chore: Support log mount options & fix private build

main.go, pkg/disk/cloud.go, pkg/disk/controllerserver.go, pkg/disk/nodeserver.go, pkg/disk/utils.go
/kind feature
Add func : allows to use auto snapshot during expanding volume of ESSD.
Fixes #
```release-note
```
```docs
```
=> Add func: allow auto snapshot during expanding volume.

build/amd/Dockerfile, build/lib/amd64-entrypoint.sh, build/multi/Dockerfile.multi, pkg/dbfs/utils.go, pkg/disk/utils.go, pkg/nas/utils.go
modify ossfs version to 1.88 and openapi scheme modify http to https
=> modify ossfs version to 1.88 and openapi scheme modify http to https

build/multi-private/amd64-entrypoint.sh
fix kylin/uos entrypoint in amd64
=> fix kylin/uos entrypoint in amd64

pkg/disk/nodeserver.go
/kind enhancement
Support k8s 1.24
Fixes #None
```release-note
```
```docs
```
=> Support globalmount path changed in k8s 1.24

pkg/dbfs/nodeserver.go, pkg/ens/nodeserver.go, pkg/metric/disk_stat_collector.go, pkg/metric/utils.go, pkg/oss/nodeserver.go, pkg/oss/utils.go
/kind bug
Support global path change in kubernetes 1.24
Fixes #None
```release-note
```
```docs
```
=> Fix globalmount path usage

build/lib/amd64-entrypoint.sh, build/lib/freezefs.sh, build/multi/Dockerfile.multi
/kind bug
-bugfix: moved the freezefs.sh to /root of csi-plugin.
-bugfix: removed the unexpected error-records in fsfreeze.log 
Fixes #
```release-note
```
```docs
```
=> modified fsfreeze.sh for advancedSnapshot.

build/multi-private/arm64-entrypoint.sh
Fixes #
```release-note
```
```docs
```
=> Add host command var

pkg/cnfs/v1beta1/base.go, pkg/oss/controllerserver.go, pkg/oss/nodeserver.go, pkg/oss/oss.go
=> add cnfs oss feature

pkg/dbfs/utils.go, pkg/disk/utils.go, pkg/nas/utils.go, pkg/utils/auth.go
=> use http in private cloud

pkg/disk/cloud.go
/kind bug
Fix describe instance history interface parameters
None
None
```release-note
```
```docs
```
=> Fix const instanceid

CONTRIBUTING.md
Signed-off-by: amolmote <amolmote201@gmail.com>
Fixes #700
=> broken link issue resolved

build/lib/amd64-entrypoint.sh, build/multi/Dockerfile.multi, pkg/nas/nas.go
update eac version from 1.0.1 to 1.0.2
=> update eac version from 1.0.1 to 1.0.2

pkg/nas/nas.go
modify don't install eac by default
=> modify don't install eac by default

build/multi-private/amd64-entrypoint.sh, build/multi-private/arm64-entrypoint.sh, pkg/nas/utils.go
/kind feature
add nas and oss support for Kylin OS on bare metal.
None
None
=> add kylin OS support on bare metal

deploy/ack/csi-plugin.yaml, deploy/ack/upgrade/upgrade_csi-plugin.sh, deploy/dbfs/csi-plugin.yaml, deploy/disk/disk-plugin.yaml, deploy/ens/csi-plugin.yaml, deploy/local/plugin.yaml, deploy/nas/nas-plugin.yaml, deploy/oss/oss-plugin-ano.yaml, deploy/oss/oss-plugin.yaml, docs/migrate/flexvolume-to-csi-disk.md
See https://github.com/kubernetes/kubernetes/issues/89477, https://github.com/kubernetes/kubernetes/issues/89477#issuecomment-603911496.
/kind cleanup
/release-note-none
```release-note
None
```
=> Stop applying the beta.kubernetes.io/os

pkg/disk/cloud.go, pkg/disk/constants.go, pkg/disk/controllerserver.go, pkg/disk/utils.go, pkg/utils/util.go
/kind feature
Protect disk from being deleted unintended
Fixes #
```release-note
```
```docs
```
=> Support custom snapshot retention

build/lib/amd64-entrypoint.sh, build/multi-private/amd64-entrypoint.sh
=> support anolis images

build/lib/amd64-entrypoint.sh, build/multi-private/amd64-entrypoint.sh, build/multi-private/arm64-entrypoint.sh
anolis use centos8 ossfs binary
=> anolis use centos8 ossfs binary

build/multi/Dockerfile.multi, build/multi/Dockerfile.multi.asi, pkg/disk/cloud.go
/kind chore
Upgrade base image from centos7.9 to alinux3. because centos7.9 is outdate
None
None
```release-note
```
```docs
```
=> Upgrade baseimg from centos7 to alinux3

build/multi/Dockerfile.multi.asi
/kind bug
Fix oidc connection leak
Fixes #
```release-note
```
```docs
```
=> Upgrade oidc isolate token

pkg/disk/nodeserver.go
hotfix disk resize error
Fixes #
```release-note
```
```docs
```
=> Fix disk resize err

pkg/disk/cloud.go, pkg/disk/nodeserver.go, pkg/disk/utils.go
Fixes #
```release-note
```
```docs
```
=> Fix ssd create with performaceLevel

go.mod, go.sum, pkg/disk/cloud.go, pkg/disk/controllerserver.go, pkg/disk/nodeserver.go, pkg/disk/utils.go, pkg/local/manager/loopdevice.go, pkg/local/server/commands.go, pkg/local/server/routers.go, pkg/log/formatter.go, pkg/log/log.go
/kind bug
Fix exists problems about loopdevice
None
None
```release-note
```
```docs
```
=> Fix file exists problems

pkg/disk/nodeserver.go
/kind bug
Fix global mountpath change after k8s upgrade
Fixes #
```release-note
```
```docs
```
=> Fix 1.24 kubelet remount issue

build/multi-private/Dockerfile.multi, build/multi-private/amd64-entrypoint.sh, pkg/oss/nodeserver.go, pkg/utils/util.go
fix internal oss endpoint bug and support alinux3 ossfs in cloud-private
=> fix internal oss endpoint bug and support alinux3 ossfs in cloud-private

build/amd/Dockerfile, build/build-all-amd.sh, build/lib/amd64-entrypoint.sh, build/multi/Dockerfile.multi, build/multi/Dockerfile.multi.asi, pkg/metric/common.go, pkg/metric/fuse_stat_collector.go, pkg/nas/controllerserver.go, pkg/nas/nas.go, pkg/nas/utils.go
=> support eac metrics

build/multi-private/amd64-entrypoint.sh, pkg/metric/fuse_stat_collector.go, pkg/nas/nodeserver.go
support eac backend meta metrics
=> support eac backend meta metrics

build/multi-private/amd64-entrypoint.sh, build/multi-private/arm64-entrypoint.sh
support arm64 and amd64 in multi-private env
=> support arm64 and amd64 in multi-private env

pkg/nas/controllerserver.go, pkg/nas/nodeserver.go, pkg/nas/utils.go, pkg/utils/util.go
=> support cpfs metrics

build/lib/amd64-entrypoint.sh, build/lib/arm64-entrypoint.sh
endpoint shell until modify for loop
=> endpoint shell until modify for loop

build/amd/Dockerfile, build/lib/amd64-entrypoint.sh, build/lib/arm64-entrypoint.sh, build/multi/Dockerfile.multi, build/multi/Dockerfile.multi.asi, pkg/cnfs/v1beta1/types.go, pkg/nas/controllerserver.go, pkg/nas/nas.go, pkg/nas/nodeserver.go, pkg/nas/utils.go, pkg/nas/utils_test.go
Fixes #
```release-note
```
```docs
```
=> support cpfs2.0 native client and fix installing ossfs failed by gpu alinux3

build/lib/amd64-entrypoint.sh
=> add yum reinstall

build/lib/amd64-entrypoint.sh, build/lib/arm64-entrypoint.sh, pkg/disk/bdf.go, pkg/disk/bdfcheck.go, pkg/disk/cloud.go, pkg/disk/disk.go, pkg/disk/nodeserver.go
/kind feature
Support vfph in bdf type instance
Fixes #
None
```release-note
```
```docs
```
=> feature: Support vhpf

pkg/nas/controllerserver.go
=> add cpfs mount protocol

pkg/nas/nodeserver.go
=> add nfsclient ProtocolServer

pkg/nas/controllerserver.go
fix dynamic cpfs-nfs can't remove pv bug
=> fix dynamic cpfs-nfs can't remove pv bug

deploy/rbac.yaml
/kind cleanup
None
Fixes #
None
```release-note
```
```docs
```
=> Chore: adjust cluster role

pkg/metric/disk_stat_collector.go, pkg/metric/nfs_stat_collector.go
/kind bug
`diskStatCollector.Update` and `nfsStatCollector.Update` is not concurrency safe when writing the map. 
Fixes #
```release-note
```
```docs
```
=> fix data race in metrics server

pkg/disk/nodeserver.go, pkg/utils/util.go
/kind feature
Custom xfs mkfs options
None
None
```release-note
```
```docs
```
=> Chore: Add xfs custom mkfs args

pkg/local/gc/gc.go, pkg/local/gc/loopdevice.go, pkg/local/gc/lvm.go, pkg/local/manager/loopdevice.go, pkg/local/nodeserver.go, pkg/local/server/commands.go
/kind feature
Support garbage collecting for lvm/loopdevice volumes on node.
Fixes #
```release-note
```
```docs
```
=> Garbage collecting for lvm/loopdevice volumes

pkg/metric/nfs_stat_collector.go
fix metrics bug for multi mountpoint
=> fix metrics bug for multi mountpoint

pkg/local/gc/lvm.go
/kind cleanup
```release-note
```
```docs
```
=> Improve lvm gc log when VG not found

build/lib/amd64-entrypoint.sh, build/lib/arm64-entrypoint.sh
/kind cleanup
Support rpm install using yum
Fixes #
```release-note
```
```docs
```
=> Chore: Add vfhp rpm install

build/lib/amd64-entrypoint.sh, build/lib/arm64-entrypoint.sh
/kind feature
You can configure to skip the installation of csiplugin-connector when it is unnecessary.
Fixes #
```release-note
set environment variable DISABLE_CSIPLUGIN_CONNECTOR=true to skip csiplugin-connector installation.
```
```docs
```
=> skip installing csiplugin-connector through env configuration

pkg/disk/controllerserver.go, pkg/disk/utils.go
/kind bug
Fix nil pointer error
None
```release-note
```
```docs
```
=> bug: Fix nil volumeattributes error

pkg/dbfs/nodeserver.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> fix(dbfs): dbfs not umounted if mount point corrupted

pkg/metric/common.go, pkg/metric/nfs_stat_collector.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> fix(nas): don't extract nas capacity statistics from system mount point

pkg/nas/controllerserver.go, pkg/nas/nas.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> fix(nas): properly cancel subpath dir quota

build/lib/amd64-entrypoint.sh
/kind bug
ensure openssl has installed, which is the dependency of ossfs
Fixes #
```release-note
```
```docs
```
=> ensure openssl has installed for ossfs 

pkg/nas/utils.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> fix(nas): subpath quota value should be rounded up to the nearest GiB

build/lib/csiplugin-connector.go, build/oss/csiplugin-connector.go, pkg/disk/controllerserver.go, pkg/disk/nodeserver.go, pkg/disk/utils.go, pkg/local/server/commands.go, pkg/metric/utils.go, pkg/nas/utils.go, pkg/oss/utils.go, pkg/utils/util.go
/kind cleanup
use fmt.Errorf(...) instead of errors.New(fmt.Sprintf(...)
unnecessary use of fmt.Sprintf
Fixes #
```release-note
NONE
```
```docs
```
=> chore: fmt modify

pkg/cpfs/controllerserver.go, pkg/local/capacity.go, pkg/local/manager/loopdevice.go, pkg/mem/nodeserver.go, pkg/nas/controllerserver.go, pkg/utils/util.go
/kind cleanup
replace loop with  xxx = append(xxx, yyy)
Fixes #
```release-note
NONE
```
```docs
```
=> chore: slice replace loop

build/amd/Dockerfile, build/lib/amd64-entrypoint.sh, build/multi/Dockerfile.multi, build/multi/Dockerfile.multi.asi, pkg/nas/nas.go
- alinas-efc-1.2-3.x86_64.rpm
- aliyun-alinas-utils-1.1-6.al7.noarch.rpm
/kind cleanup
Fixes #
```release-note
```
```docs
```
=> nas: upgrade alinas rpm packages

build/multi/Dockerfile.controller
/kind feature
Add disk controller dockerfile
None
None
```release-note
```
```docs
```
=> chore: Add disk controller dockerfile

build/lib/amd64-entrypoint.sh, build/multi-private/amd64-entrypoint.sh, build/multi-private/arm64-entrypoint.sh
/kind bug
centos7.0_ossfs for anolis 7 with openssl1.0.2
centos8_ossfs for anolis 8 with openssl1.1.1 
Fixes #
related issue: 792
```release-note
```
```docs
```
=> bugfix: install different ossfs version for anolis7/8

build/amd/Dockerfile, build/lib/amd64-entrypoint.sh, build/multi-private/Dockerfile.multi, build/multi-private/amd64-entrypoint.sh, build/multi/Dockerfile.multi
/kind bug
update ossfs to v1.88.1, in this version, fix:
1 object seems as a x-troff-man MIME type when create a directory with specified name.
2 wrong request head setting for specified kms id for encryption.
Fixes #
```release-note
```
```docs
```
=> ossfs update to v1.88.1

pkg/disk/utils.go
/kind feature
Support ecs instance attached cloud disk count auto detected
None
None
```release-note
None
```
```docs
```
=> feature: support disk auto detected

build/lib/amd64-entrypoint.sh, build/lib/arm64-entrypoint.sh, pkg/disk/bdf.go, pkg/disk/nodeserver.go, pkg/metric/utils.go
/kind bug
Fix bdf logic
None
None
```release-note
```
```docs
```
=> BugFix: fix bdf logics error

pkg/nas/nodeserver.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> fix(nas): skips mounting if target path already mounted

pkg/local/lib/parser.go, pkg/local/server/commands.go, pkg/metric/common.go, pkg/metric/disk_stat_collector.go, pkg/metric/local_stat_collector.go, pkg/metric/metric.go, pkg/metric/nfs_stat_collector.go, pkg/metric/pfs_stat_collector.go, pkg/metric/utils.go, pkg/utils/util.go
/kind feature
/kind cleanup
Some Cleanups.
Export LVM VG size/free metrics 
```release-note
New prometheus metrics about local LVM volume VG size/free
```
```docs
```
=> Export LVM VG size/free metrics

pkg/pov/node.go
/kind bug
Fix pov topology key value
None
None
```release-note
```
```docs
```
=> bugfix: fix pov topology key

main.go, pkg/metric/collector.go, pkg/metric/common.go, pkg/metric/disk_stat_collector.go, pkg/metric/fuse_stat_collector.go, pkg/metric/local_stat_collector.go, pkg/metric/metric.go, pkg/metric/nfs_stat_collector.go, pkg/metric/pfs_stat_collector.go
/kind cleanup
we have multiple drivers and multiple metric collectors in one binary. Only enable metric collectors that are related to the currently enabled drivers.
Once this or #807 is merged, I will edit the other one accordingly.
```release-note
CSI plugin now only export metrics about the enabled drivers
```
```docs
```
=> metric: only enable when related driver is enabled

pkg/metric/fuse_stat_collector.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> fix: efc metrics not collected

build/arm/entrypoint.sh, build/lib/amd64-entrypoint.sh, build/lib/arm64-entrypoint.sh, build/lib/csiplugin-connector.go, build/lib/csiplugin-connector.service, build/multi-private/amd64-entrypoint.sh, build/multi-private/arm64-entrypoint.sh, build/multi-private/csiplugin-connector.go, build/multi-private/csiplugin-connector.service, build/oss/csiplugin-connector.go, build/oss/csiplugin-connector.service, build/oss/entrypoint.sh
/kind cleanup
Change csiplugin-connector pid file
None
None
```release-note
```
```docs
```
=> cleanup: change connector pid file to /var/run/csiplugin

pkg/dbfs/utils.go, pkg/disk/utils.go, pkg/ens/nodeserver.go, pkg/ens/utils.go
/kind bug
when "grep" exists in mount command output, grep -v grep will filter all mountpoints, unexpected
None
None
```release-note
```
```docs
```
=> bugfix: remove grep -v grep commands in mount output

pkg/disk/cloud.go
/kind bug
disk/createDisk: fix typo
Fixes #
```release-note
NONE
```
```docs
```
=> disk/createDisk: fix typo

pkg/oss/nodeserver.go, pkg/oss/utils.go
Fixes #
```release-note
```
```docs
```
=> bugfix: remove empty OSS mount point to avoid  mount point retain problem

build/multi-private/Dockerfile.multi, build/multi/Dockerfile.multi, build/multi/Dockerfile.multi.asi
/kind cleanup
Specifies the version of build image
None
None
```release-note
```
```docs
```
=> Chore: Specifies the version of build image

build/lib/amd64-entrypoint.sh, build/lib/arm64-entrypoint.sh, deploy/ecs/csi-plugin.yaml, deploy/nonecs/csi-plugin.yaml, pkg/common/nodeserver.go, pkg/common/start.go, pkg/cpfs/cpfs.go, pkg/dbfs/dbfs.go, pkg/disk/disk.go, pkg/ens/ens.go, pkg/local/local.go, pkg/losetup/losetup.go, pkg/losetup/truncate.go, pkg/lvm/lvm.go, pkg/mem/mem.go, pkg/mounter/connector_mounter.go, pkg/nas/controllerserver.go, pkg/nas/mounter.go, pkg/nas/nas.go, pkg/nas/nodeserver.go, pkg/nas/utils.go, pkg/nas/utils_test.go, pkg/oss/oss.go, pkg/utils/loopdevice.go, pkg/utils/util.go
/kind cleanup
Fixes #
```release-note
```
```docs
```
=> refactor the mounter implementation of nas plugin

main.go
/kind feature
Change default pprof port
None
None
```release-note
```
```docs
```
=> Perf: change default pprof port

deploy/nonecs/csi-driver.yaml, deploy/nonecs/csi-plugin.yaml, deploy/nonecs/csi-provisioner.yaml, deploy/nonecs/rbac.yaml
ECS manifests are updated in #837 , sync non-ECS manifests here.
I've written a tool to automatically sync these manifests from ACK cluster.
```release-note
NONE
```
```docs
```
=> docs: sync non-ecs manifest with ecs

pkg/disk/utils.go
/kind feature
skip disk stock check of describe nodetype resources
Fixes #
```release-note
```
```docs
```
=> feature: skip disk stock check of describe nodetype resources

pkg/disk/utils.go
/kind bug
Fix diskCatalog type
Fixes #
```release-note
```
```docs
```
=> feature: skip disk stock check

pkg/common/controllerserver.go, pkg/common/nodeserver.go, pkg/common/start.go, pkg/cpfs/controllerserver.go, pkg/dbfs/nodeserver.go, pkg/disk/controllerserver.go, pkg/disk/nodeserver.go, pkg/ens/controllerserver.go, pkg/ens/nodeserver.go, pkg/local/controllerserver.go, pkg/local/nodeserver.go, pkg/lvm/controllerserver.go, pkg/mem/controllerserver.go, pkg/nas/controllerserver.go, pkg/nas/nodeserver.go, pkg/oss/controllerserver.go, pkg/oss/nodeserver.go, pkg/pov/controller.go, pkg/pov/pov.go
/kind cleanup
We have many duplicated parameter checking logics, and also many missing ones.
This PR systematically checks all required parameters required by CSI. And removes the duplicated ones scattered everywhere.
This PR also changes the recently added POV driver to use `common.RunCSIServer`, so it is also covered by the validator.
```release-note
NONE
```
```docs
```
=> Validate that all parameters required by CSI spec is provided

go.mod, pkg/cpfs/controllerserver.go, pkg/dbfs/controllerserver.go, pkg/dbfs/identityserver.go, pkg/disk/controllerserver.go, pkg/disk/identityserver.go, pkg/disk/nodeserver.go, pkg/ens/identityserver.go, pkg/local/controllerserver.go, pkg/local/identityserver.go, pkg/local/nodeserver.go, pkg/local/nodeutils.go, pkg/local/server/commands.go, pkg/local/server/routers.go, pkg/lvm/controllerserver.go, pkg/lvm/identityserver.go, pkg/lvm/nodeserver.go, pkg/mem/controllerserver.go, pkg/mem/identityserver.go, pkg/mem/mem.go, pkg/mem/nodeserver.go, pkg/nas/controllerserver.go, pkg/oss/controllerserver.go
/kind cleanup
run: `go fix ./...`, then reorder the imports for each modified file.
Change imports of golang.org/x/net/context to context
```release-note
NONE
```
```docs
```
=> go fix: fixed context

pkg/metric/utils.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> fix(metrics): get disk pv globalmount path correctly

pkg/mounter/helper.go, pkg/nas/utils.go, pkg/nas/utils_test.go
/kind/bug
Fixes #
```release-note
```
```docs
```
=> Fix nfs vers parsing

hack/check-vendor.sh
/kind cleanup
Add vendor check actions
None
```release-note
```
```docs
```
=> chore: add vendor check actions

pkg/common/constants.go, pkg/disk/cloud.go, pkg/disk/constants.go, pkg/disk/controllerserver.go, pkg/disk/utils.go, pkg/ens/utils.go
/kind feature
Add disk tags about PV/PVC. And some minor cleanup.
```release-note
Added disk tags about PV/PVC, mimics the in-tree drivers: `kubernetes.io/created-for/pvc/name`, `kubernetes.io/created-for/pvc/namespace`, `kubernetes.io/created-for/pv/name`
```
```docs
```
=> Add disk tags about PV/PVC

pkg/disk/cloud.go, pkg/disk/constants.go, pkg/disk/controllerserver.go
/kind cleanup
properly set error code for:
* not existing snapshot
* volume already created with the same name but different parameters
Fixes #
```release-note
NONE
```
```docs
```
=> disk/CreateVolume: properly set error code

deploy/ecs/rbac.yaml, deploy/nonecs/rbac.yaml
/kind bug
Fixes: eb41b2d6 refactor UpdateNode
Fixes #
```release-note
NONE
```
```docs
```
=> rbac: add node patch permission

deploy/ecs/csi-provisioner.yaml, deploy/ecs/rbac.yaml, deploy/nonecs/csi-provisioner.yaml, deploy/nonecs/rbac.yaml
/kind bug
Pod can now be rescheduled if the node is deleted.
https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/pull/139
```release-note
NONE
```
```docs
```
=> update external provisioner to v3.5.0

pkg/disk/utils.go
/kind bug
It seems that this API sometimes returns valid json, but without regionID. Trying to identify the problem.
Fixes #
```release-note
NONE
```
```docs
```
=> adding checks to getInstanceDoc

pkg/metric/fuse_stat_collector.go, pkg/utils/util.go
/kind cleanup
Remove useless code
None
None
```release-note
```
```docs
```
=> cleanup: delete RemoveAll MkdirAll method

pkg/oss/controllerserver.go, pkg/oss/nodeserver.go
Fixes #
```release-note
```
```docs
```
=> oss-feat: add ro mount options in ReadOnly mode

pkg/nas/controllerserver.go, pkg/nas/nodeserver.go, pkg/nas/utils.go, pkg/utils/volume_locks.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> nas: serialize operations on the same volume

pkg/disk/cloud.go, pkg/disk/cloud_test.go, pkg/disk/ecsinterface.go, pkg/disk/ecsmock.go
/kind cleanup
Increase test coverage.
```release-note
NONE
```
```docs
```
=> Unit test for deleteDisk

build/lib/amd64-entrypoint.sh, build/lib/arm64-entrypoint.sh, pkg/disk/bdf.go, pkg/metric/utils.go
/kind feature
Enable bdf check for pov driver in entrypoint
Fixes #
None
```release-note
```
```docs
```
=> feature: enable bdf check for pov driver

pkg/disk/cloud.go, pkg/disk/disk.go, pkg/ens/ens.go, pkg/ens/utils.go
/kind cleanup
simplify the code.
Fixes #
Why do we need this logic in the first place?
```release-note
NONE
```
```docs
```
=> disk/ens: optimize AttachMutex

build/lib/amd64-entrypoint.sh, build/lib/arm64-entrypoint.sh
/kind feature
Bump vfph helper version to 0.18
Fixes #
```release-note
```
```docs
```
=> Bump: bump vfph helper to 0.1.8

pkg/disk/nodeserver.go
/kind feature
Support protocol with kata of mount disk with tmpfs. will replaced with  CSI 3.0 protocol
Fixes #
```release-note
```
```docs
```
=> Feature: ignore tmpfs mountpoint check

test/csi-sanity/csi-sanity-disk.yaml
Fixes #
```release-note
NONE
```
```docs
```
=> add a manifest that we can run csi-sanity in k8s

pkg/cloud/metadata/ecs.go, pkg/cloud/metadata/k8s.go, pkg/cloud/metadata/metadata.go, pkg/cloud/metadata/openapi.go
/kind feature
immutableProvider is a wrapper around providers that always returns the same value for a specific key. It caches the result and logs when the key is seen for the first time.
logs look like:
```
time="2023-10-11T21:13:35+08:00" level=info msg="retrive metadata" key=RegionID provider=ECS value=cn-beijing
```
```release-note
NONE
```
```docs
```
=> metadata: add logging and cache

build/lib/amd64-entrypoint.sh
/kind bug
Fixes #
```release-note
```
```docs
```
=> retry alinas-utils installation

pkg/disk/constants.go
/kind feature
Support restricted resource code error retry
None
None
```release-note
```
```docs
```
=> Feature: support restricted resource code error retry

build/lib/amd64-entrypoint.sh, build/multi-private/amd64-entrypoint.sh, build/multi-private/arm64-entrypoint.sh
/kind bug
alinux2 can not be detected so that efc not installed properly.
Fixes #
```release-note
```
```docs
```
=> fix host_os detection

pkg/oss/controllerserver.go
/kind cleanup
Support reading kube-config from command line
Fixes #
```release-note
```
```docs
```
=> Cleanup: support read kubecfg from command line

pkg/disk/disk.go, pkg/disk/nodeserver.go, pkg/utils/config.go
/kind bug
/kind cleanup
now all configs can either be set by configmap or env variable, with env takes precedence.
also fixed a bug that isDiskMetricEnable cannot be set to false by configmap
```release-note
NONE
```
```docs
```
=> disk: refactor config options

pkg/utils/io.go
/kind bug
In 18f98b1, we fixed burstable path, but guaranteed QoS does not follow this pattern, and is still wrong.
Fixes 18f98b1c2b85ff2ec2072cf291a3e88c036fc4ea
```release-note
NONE
```
```docs
```
=> utils: fix guaranteed QoS blkio cgroup path

deploy/ecs/rbac.yaml, deploy/nonecs/rbac.yaml
Fixes #
```release-note
```
```docs
```
=> add rbac for csi-plugin to get svc of storage-monitor

pkg/disk/nodeserver.go
/kind cleanup
Support cleanup when block device mount failed
Fixes #
```release-note
```
```docs
```
=> Chore: support block device mount failed

pkg/metric/disk_stat_collector.go
The current disk I/O hang alert is inaccurate and redundant. Users can rely directly on EBS's own monitoring and alerting mechanism.
/kind cleanup
Fixes #
The current disk I/O hang alert is inaccurate and redundant. Users
can rely directly on EBS's own monitoring and alerting mechanism.
```release-note
```
```docs
```
=> remove disk I/O hang alert according to /proc/diskstats

pkg/dbfs/nodeserver.go, pkg/disk/nodeserver.go, pkg/ens/nodeserver.go, pkg/utils/mounter.go
/kind cleanup
CSI says this path is created by CO (kubernetes) since v1.0.0-rc3:
> CO SHALL be responsible for creating the directory if it does not exist.
So CO should delete it rather than us.
```release-note
NONE
```
```docs
```
=> NodeUnstageVolume: don't delete target dir

deploy/ecs/csi-provisioner.yaml, deploy/nonecs/csi-provisioner.yaml
/kind cleanup
We never return InUse error, so this should have no impact. This should greatly reduce the memory consumption, so shrink the limits.
```release-note
The memory footprint of provisioner is greatly reduced.
```
```docs
```
=> disable podInformer in external-resizer

pkg/nas/nodeserver.go, pkg/nas/utils.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> fix(nas): set /proc/sys/sunrpc/tcp_slot_table_entries to 128

pkg/mounter/fuse_containerized_mounter.go, pkg/mounter/ossfs.go, pkg/mounter/ossfs_test.go, pkg/oss/nodeserver.go, pkg/oss/nodeserver_test.go
/kind bug
Support sts authtype in ossfs-containerized version.
Fixes #
```release-note
```
```docs
```
=> fix: support sts authtype in containerized version

pkg/oss/controllerserver.go, pkg/oss/nodeserver.go
/kind feature
support aes256, kms, byok encryption in containerized version
Fixes #
```release-note
```
```docs
```
=> feat-oss: encryption kms, aes236, byok

pkg/cloud/metadata/k8s.go, pkg/cloud/metadata/k8s_test.go
/kind feature
metadata: support for old ecs-instance-id label
Fixes #
```release-note
```
```docs
```
=> metadata: support for old ecs-instance-id label

build/fuse-clients/ossfs/Dockerfile, build/fuse-clients/ossfs/entrypoint.sh, pkg/mounter/fuse_containerized_mounter.go, pkg/mounter/fuse_containerized_mounter_test.go, pkg/mounter/helper.go, pkg/mounter/ossfs.go
/kind feature
allow users add customized annotations or labels on fuse pods.
Fixes #
```release-note
```
```docs
```
=> support customized annotations and labels on fuse pod

build/fuse-clients/ossfs/entrypoint.sh, pkg/mounter/ossfs.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> ossfs entrypoint should not delay termination if no mountpoints

pkg/disk/utils.go
/kind cleanup
Add logs for rund expanding
Fixes #
```release-note
```
```docs
```
=> chore: add logs for rund expanding

deploy/ecs/csi-provisioner.yaml
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> deploy: remove GA feature gate

pkg/disk/controllerserver.go
/kind feature
Calling the ControllerExpandVolume interface without disk type checking
Fixes # None
None
```release-note
```
```docs
```
=> feature: support all disk types auto resize

pkg/disk/cloud.go, pkg/disk/constants.go
/kind feature
ECS will soon relax the size limit of cloud_auto and cloud_essd PL0 disks. We will follow them.
Fixes #
```release-note
cloud_auto/cloud_essd PL0 disks can be as small as 1GiB now (given ECS OpenAPI supports this, ETA Nov.-Dec., 2023).
```
```docs
```
=> disk: remove the size limit of some categories

build/lib/amd64-entrypoint.sh, build/lib/arm64-entrypoint.sh
/kind cleanup
Bump up vfhp version
Fixes # None
```release-note
None
```
```docs
```
=> chore: bump up vfhp version

pkg/disk/cloud.go, pkg/disk/constants.go, pkg/disk/utils.go, pkg/ens/utils.go, pkg/nas/nodeserver.go
/kind cleanup
fix typo reported by misspell, which is show in the goreportcard in our readme.
Fixes #
```release-note
NONE
```
```docs
```
=> fix typo reported by misspell

pkg/disk/cloud.go, pkg/disk/constants.go, pkg/disk/controllerserver.go
/kind cleanup
* NotFound if attaching not existing volume
* NotFound if attaching to not existing node
to comply with CSI spec
Fixes #
This can be covered by CSI sanity once we enable ADController.
```release-note
NONE
```
```docs
```
=> disk: refine attach error codes

pkg/nas/controllerserver.go, pkg/nas/utils.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> fix(nas): fix error handling when deleting mounttarget not existing

pkg/disk/nodeserver.go, pkg/utils/mounter.go
=> [v1.26] disk: fix unmountDuplicateMountPoint to handle no data disk node

pkg/metric/collector.go, pkg/metric/kubelet_stats_summary_collector.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> Cherry pick #949 fix kubelet stats summary collector panic

pkg/oss/nodeserver.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> skip removal if mountPoint does not exist

pkg/disk/nodeserver.go, pkg/disk/utils.go
/kind feature
supposed to be passed as PVC annotation.
combined with alibabacloud.com/createdisk-arn, this can support multi-tenant use-case.
Fixes #
```release-note
NONE
```
```docs
```
=> support alibabacloud.com/kms-key-id CreateVolume parameter

pkg/oss/nodeserver.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> umount ossfs global mountpoint if corrupted

build/lib/amd64-entrypoint.sh, build/lib/arm64-entrypoint.sh, build/multi-private/amd64-entrypoint.sh, build/multi-private/arm64-entrypoint.sh
/kind cleanup
This can avoid conflict if the version of provisioner and plugin is different.
updates #865
```release-note
NONE
```
```docs
```
=> skip setup for provisioner

build/multi-private/Dockerfile.multi, build/multi/Dockerfile.controller, build/multi/Dockerfile.multi, build/multi/Dockerfile.multi.asi
/kind bug
Fixes #
```release-note
NONE
```
```docs
```
=> fix build version injection

.dockerignore
Starting from go1.18, `go build` will embed git revision in the output automatically, which can be viewed by `go version -m /path/to/output`. We may still use partial clone to reduce the size of .git directory.
/kind feature
Fixes #
```release-note
NONE
```
```docs
```
=> enable embed git revision in binary

.github/ISSUE_TEMPLATE/bug-report.md
/kind cleanup
to be CSI and Alibaba Cloud specific
Fixes #
```release-note
NONE
```
```docs
```
=> update issue template

build/lib/amd64-entrypoint.sh, build/lib/arm64-entrypoint.sh
/kind bug
configure mlocate setting to avoid logs of headobject req caused by scan.
Fixes #
```release-note
```
```docs
```
=> fix: configure mlocate cron.daily

pkg/local/capacity.go
Reverts kubernetes-sigs/alibaba-cloud-csi-driver#975
=> Revert "Unified loopdevice name"

pkg/disk/attachdetach_slot.go, pkg/disk/attachdetach_slot_test.go
/kind bug
Fixes: 8ff3b507616165e9aedf81907db2df9c081ad7a3
```release-note
NONE
```
```docs
```
=> fix panic when using parallel attach detach

pkg/disk/cloud.go, pkg/nas/controllerserver.go
/kind feature
Add specific http header for private cloud to classified resource
Fixes #
```release-note
```
```docs
```
=> feature: support specific http header

pkg/utils/auth.go, pkg/utils/crypto/aes.go, pkg/utils/crypto/ramtoken.go
/kind cleanup
Refact ram token decrypt
Fixes #
```release-note
```
```docs
```
=> chore: refact token decrypt

pkg/disk/cloud.go, pkg/disk/constants.go
/kind bug
Fixes #
```release-note
In cn-north-2-gov-1 region, skip unsupported PL0 and try other configs.
```
```docs
```
=> disk: fallback on unsupported PL

pkg/disk/utils.go
/kind cleanup
make the error message cleaner.
Fixes #
```release-note
NONE
```
```docs
```
=> avoid two level of status.Error

pkg/nas/cloud/const.go, pkg/nas/cloud/nas_client_v2.go, pkg/nas/cloud/utils.go, pkg/nas/subpath_controller.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> fix(nas): extreme subpath provision

deploy/ecs/rbac.yaml
/kind cleanup
organize csi rbac privilege
Fixes #None
None
```release-note
```
```docs
```
=> feat: organize csi rbac privilege

deploy/ecs/csi-plugin.yaml, deploy/ecs/csi-provisioner.yaml, deploy/nonecs/csi-plugin.yaml, deploy/nonecs/csi-provisioner.yaml, deploy/nonecs/rbac.yaml, test/csi-sanity/csi-sanity-disk.yaml
/kind bug
ServiceAccount is a depreciated alias for ServiceAccountName. Use serviceAccountName instead.
Fixes: 3c75e06341bbe0b70f857bffc9b8e6dd3e7a7ad7
```release-note
NONE
```
```docs
```
=> update serviceAccountName in Pod

pkg/disk/nodeserver.go, pkg/disk/utils.go
/kind cleanup
add/correct logs, correct variable name
Fixes #
```release-note
NONE
```
```docs
```
=> disk: NodeGetInfo cleanups

SECURITY.md, SECURITY_CONTACTS
/kind ducumentation
/kind bug
Add more security infos 
Fixes #1022
```release-note
```
```docs
```
=> Add more security reported infos

deploy/chart/templates/rbac.yaml
/kind bug
We used to use the role alicloud-csi-plugin for both node and controller. To avoid any issue for users that upgrade node/controller separately, rename the role to alicloud-csi-node, so that it will not overwrite the old role.
Fixes #
```release-note
NONE
```
```docs
```
=> deploy: rename sa/role plugin -> node

go.mod, pkg/disk/controllerserver.go, pkg/disk/utils.go
/kind cleanup
github.com/golang/protobuf is replaced by google.golang.org/protobuf
Fixes #
```release-note
NONE
```
```docs
```
=> remove direct deps on github.com/golang/protobuf

deploy/chart/Chart.yaml, deploy/chart/values.yaml
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> helm: bump image version to release v1.4.0

deploy/chart/templates/plugin.yaml, test/csi-sanity/csi-sanity-disk.yaml
/kind bug
Fix: fecd7ec6c2fe6efff14ab66c9322ece94f5df628
```release-note
NONE
```
```docs
```
=> helm: fix service account name

pkg/disk/cloud.go, pkg/disk/controllerserver.go
/kind feature
When 'diskid' is present in the annotations and volume can be created statically, add custom tags and some default tags to the disk.
Fixes #
```release-note
NONE
```
```docs
```
=> feat: tag disk when creating static volume

pkg/cloud/ecsinterface.go, pkg/cloud/ecsmock.go, pkg/disk/cloud.go, pkg/disk/cloud_test.go, pkg/disk/controllerserver.go
/kind bug
/kind cleanup
retry ResizeDisk in case of last order processing
Maybe this disk is just created?
Also refactored deleteDisk to use wait.PollImmediateWithContext
Fixes CSI sanity case: expandvolume [controller server] [it] should work
```release-note
NONE
```
```docs
```
=> retry ResizeDisk in case of last order processing

pkg/features/features.go, pkg/mounter/ossfs.go, pkg/oss/nodeserver.go
/kind feature
Allow users to bump  the version of ossfs to 1.91.2 by feature-gate **UpdatedOssfsVersion**.
Fixes #
```release-note
```
```docs
```
=> feat: support UpdatedOssfsVersion feature-gate

pkg/disk/device_manager.go, pkg/disk/device_manager_test.go, pkg/disk/nodeserver.go
/kind bug
do not assume the device path ends with the device name.
Fixes: 9a71d43bb92d866497e6da11ea8281bd940d5b27
```release-note
NONE
```
```docs
```
=> disk: fix sysConfig

build/multi/Dockerfile.multi.asi
/kind bug
apply the patch from ebbe6dda84b9806bf3b168243e76003782ad5b74
Fixes #
```release-note
NONE
```
```docs
```
=> build: update asi Dockerfile

pkg/cloud/metadata/ecs.go
/kind bug
Fixes #
```release-note
NONE
```
```docs
```
=> cloud/metadata: retry on http 429

pkg/disk/device_manager.go, pkg/disk/device_manager_test.go
/kind cleanup
docs of syscall recommends the unix package. And latter enables simpler code.
Fixes #
```release-note
NONE
```
```docs
```
=> disk/device_manager: replace syscall with unix package

deploy/chart/templates/controller.yaml, deploy/chart/templates/plugin.yaml, deploy/chart/values.yaml
/kind feature
Add featuregate parameters to provisioner & plugin
Fixes #
```release-note
```
```docs
```
=> feautre: add featuregate parameters

pkg/oss/utils.go, pkg/oss/utils_test.go
Fixes #
```release-note
```
```docs
```
=> fix: compatible with the old OSS accelerator endpoint

pkg/disk/nodeserver.go, pkg/nas/nodeserver.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> fix: rund protocol file path

deploy/chart/Chart.yaml, deploy/chart/templates/_utils.tpl, deploy/chart/templates/controller.yaml, deploy/chart/templates/plugin.yaml, deploy/chart/templates/rbac.yaml, deploy/chart/values.yaml
/kind feature
Fixes #
```release-note
NONE
```
```docs
```
=> helm: add separated local driver

main.go, pkg/cloud/metadata/k8s.go, pkg/pov/node.go, pkg/pov/pov.go
/kind feature
Fixes #
```release-note
```
```docs
```
=> pov driver mount tmpfs when NodePublishVolume

deploy/chart/templates/controller.yaml, deploy/chart/templates/plugin.yaml
/kind bug
/kind cleanup
Removed all unnecessary occurrence of /var/lib/kubelet, controller should not depends on this.
Registrars don't need the whole kubelet-dir
Fixes local plugin crash if /var/lib/kubelet/csi-plugins/localplugin.csi.alibabacloud.com does not exist in advance.
Fixes #
```release-note
NONE
```
```docs
```
=> helm: less dependent on /var/lib/kubelet

pkg/nas/nodeserver.go
/kind bug
/kind feature
Fixes #
```release-note
```
```docs
```
=> NAS: make rund protocol work without skipmount

build/multi/Dockerfile.multi
/kind bug
to resolve false positive when probing existing disk data.
Fixes #
```release-note
Reduced the possibility of failing to mount new encrypted disk.
```
```docs
```
=> build our own blkid

pkg/utils/util.go
/kind bug
fix false warning:
GetNvmeDeviceByVolumeID: udevadm did not know serial number for nvme4n1
Fixes: a4afaa44f77
```release-note
NONE
```
```docs
```
=> disk: fix false warning about udevadm

test/e2e-kubernetes/disk-manifest.yaml
Fixes #
```release-note
NONE
```
```docs
```
=> Kubernetes e2e external storage manifest

build/multi/Dockerfile.multi, main.go, test/cluster/cluster-template.json, test/cluster/cluster_setup.sh, test/cluster/gather_logs.sh, test/csi-sanity/coverage.yaml, test/csi-sanity/kustomization.yaml
/kind feature
Fixes #
```release-note
NONE
```
```docs
```
=> test: scripts for integration tests and collect coverage

OWNERS
Fixes #
```release-note
NONE
```
```docs
```
=> add more reviewers

pkg/disk/utils.go, pkg/disk/utils_test.go
/kind feature
To be consistent with snapshot tags, and allow arbitrary characters in key or value.
Fixes #
```release-note
Custom disk tags now can be specified as "diskTags/key: value", in addition to the original format.
```
```docs
```
=> disk: support specify disk tags with diskTags/key: value

pkg/disk/cloud.go, pkg/disk/controllerserver.go, pkg/disk/utils.go, pkg/disk/utils_test.go
/kind bug
or we may get IdempotentParameterMismatch when retrying.
Fixes #
```release-note
fix possible IdempotentParameterMismatch error when retrying CreateVolume.
```
```docs
```
=> disk: ensure the tags order is consistent

build/lib/amd64-init.sh, build/lib/csiplugin-connector.go, build/multi-private/Dockerfile.multi, build/multi-private/amd64-entrypoint.sh, build/multi-private/csiplugin-connector.go, pkg/oss/nodeserver.go, pkg/oss/utils.go
/kind cleanup
Jindofs has not been maintained on CSI for some time. Fuse will eventually need to be run in a containerized way and jindofs needs to be re-adapted in the future.
Fixes #
```release-note
```
```docs
```
=> cleanup: remove jindofs temporarily

test/cluster/gather_logs.sh
/kind bug
or we may get just a tar of symlinks
Fixes #
```release-note
NONE
```
```docs
```
=> test: dereference while gather logs

deploy/chart/values.yaml
/kind feature
/kind bug
Fix panic when node is not reachable.
Support LVM block volume.
Reject provisioning of other block volume.
Fixes #
```release-note
local: Fix panic when node is not reachable.
local: Support LVM block volume.
local: Reject provisioning of other block volume.
```
```docs
```
=> local: bump to v0.1.0

pkg/mounter/ossfs.go
/kind feature
bump ossfs vertsion to 1.91.3, related changelogs here:
https://github.com/aliyun/ossfs/blob/master/ChangeLog
Fixes #
```release-note
```
```docs
```
=> ossfs: bump to 1.91.3

build/multi-private/Dockerfile.multi, build/multi/Dockerfile.controller, build/multi/Dockerfile.multi, build/multi/Dockerfile.multi.asi, go.mod, go.sum, pkg/disk/cloud.go, pkg/disk/controllerserver.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> bump golang to 1.22.3

build/lib/init.sh, build/multi/Dockerfile.multi
/kind feature
Fixes #
```release-note
Support for some advanced NAS features (TLS) on Ubuntu
```
```docs
```
=> build: install alinas-utils on Ubuntu

docs/migrate/flexvolume-to-csi-disk.md, pkg/disk/controllerserver.go, pkg/disk/nodeserver.go, pkg/metric/disk_stat_collector.go, pkg/utils/error_types.go, pkg/utils/error_types_test.go
/kind cleanup
Remove SPM and non-ascii chars in log
NONE
=> Remove SPM and non-ascii chars in log

docs/ram-policies/nas.json
Fixes #
```release-note
```
```docs
```
=> doc: add ram policy example for nas driver

build/lib/init.sh, build/multi/Dockerfile.multi, build/multi/Dockerfile.multi.asi
/kind feature
/kind cleanup
Fixes #
```release-note
Now we can use alinas-utils to mount nas with tls options on alinux3.
```
```docs
```
=> update alinas-utils rpm package to support tls mount on alinux3

deploy/chart/templates/plugin.yaml, pkg/disk/bdf.go, pkg/disk/device_manager.go, pkg/disk/device_manager_test.go, pkg/disk/nodeserver.go, pkg/ens/nodeserver.go, pkg/utils/cgroup/io.go, pkg/utils/cgroup/io_test.go, pkg/utils/cgroup/pod.go, pkg/utils/cgroup/pod_test.go, pkg/utils/io.go, pkg/utils/io/device.go, pkg/utils/io/file.go, pkg/utils/io/file_test.go, pkg/utils/io/io_darwin.go, pkg/utils/io/io_linux.go, pkg/utils/io_darwin.go, pkg/utils/io_test.go, pkg/utils/util.go
/kind feature
Fixes #
```release-note
IO limits features now supports CGroup V2
```
```docs
```
=> CGroup V2 support

pkg/disk/cloud.go, pkg/disk/disk.go
/kind bug
Fix IsVFNode check error in provisioner
None
```release-note
```
```docs
```
=> bugfix: Fix IsVFNode check error in provisioner

deploy/chart/templates/plugin.yaml
/kind bug
our old daemonset is always called csi-plugin, so check for pluginname instead of node pool key.
Fixes upgrade for values-edge.yaml
Fixes: d8de0a61316932eaee4cb80a65401bd25093b260
```release-note
NONE
```
```docs
```
=> deploy: ensure daemonset can upgrade

pkg/nas/controllerserver.go, pkg/nas/nodeserver.go, pkg/nas/utils.go, pkg/utils/volume_locks.go
/kind cleanup
Fixes #
```release-note
```
```docs
```
=> Cherry pick #861 nas: serialize operations on the same volume 

pkg/oss/utils.go, pkg/oss/utils_test.go
/kind feature
support concatenated mountoptions like -ogid=1000,uid=1000, which is widely accepted by FUSE daemon
Fixes #
```release-note
```
```docs
```
=> oss: support concatenated mountoptions like -ogid=1000,uid=1000

deploy/chart/templates/controller.yaml
/kind cleanup
* Lower the priority from system-node-critical to system-cluster-critical. csi-plugin should have higher priority, since provisioner can still be scheduled to another node.
* Don't tolerate node.cloudprovider.kubernetes.io/uninitialized, we need CNI to work.
* Remove privileged, hostPath, hostPID. We don't need them.
* With the above changes, csi-provisioner pod should be able to run on ECI. Change the affinity from required to preferred.
Fixes #
```release-note
NONE
```
```docs
```
=> deploy: optimize controller template

pkg/oss/controllerserver.go, pkg/oss/nodeserver.go, pkg/oss/utils.go, pkg/oss/utils_test.go
/kind feature
Allows customized roleName for STS.
Fixes #
```release-note
```
```docs
```
=> feat(OSS): allow customized roleName for STS

pkg/disk/constants.go, pkg/disk/utils.go
/kind feature
Support new filesystem type
Fixes #
None
```release-note
```
```docs
```
=> chore: Add new support filesystem type

build/lib/init.sh, deploy/chart/templates/_utils.tpl, deploy/chart/templates/plugin.yaml, deploy/chart/values.yaml
/kind feature
deploy: support customized kubelet root dir
Fixes #
```release-note
Customized kubelet root dir is supported in the Helm chart
```
```docs
```
=> deploy: support customized kubelet root dir

pkg/disk/cloud.go
/kind feature
Add clusterid tag to static provision volume
Fixes #
```release-note
```
```docs
```
=> Add clusterid tag to static provision volume

deploy/chart/templates/plugin.yaml, deploy/chart/templates/rbac.yaml
/kind cleanup
Fixes #
related #1124
```release-note
NONE
```
```docs
```
=> deploy: refine for disk only deployments

pkg/disk/utils.go, pkg/disk/utils_test.go
/kind bug
disk: fix performance level not effective
Fixes: c593a375765d42237fc399fe530ad0fa6840c5bb
Fixes: #1083
```release-note
NONE
```
```docs
```
=> disk: fix performance level not effective

deploy/chart/templates/controller.yaml
/kind feature
Add env configuration
Fixes #
```release-note
```
```docs
```
=> Add new env for private cloud

pkg/disk/cloud.go, pkg/disk/utils.go, pkg/nas/cloud/nas_client_v1.go, pkg/nas/cloud/nas_client_v2.go, pkg/nas/filesystem_controller.go, pkg/utils/http/header.go, pkg/utils/http/header_test.go
/kind feature
Fixes #
```release-note
NONE
```
```docs
```
=> set x-acsproxy-ascm-context header globally

pkg/disk/cloud.go, pkg/disk/utils.go, pkg/disk/utils_test.go
/kind bug
Backport of the first commit of #1073.
#1025 #1000 also included to avoid conflict.
Fixes #
Manually resolved 2 trivial conflicts about import.
```release-note
fix possible IdempotentParameterMismatch error when retrying CreateVolume.
```
```docs
```
=> [1.26] disk: ensure the tags order is consistent

pkg/disk/nodeserver.go
User may upgrade the kubelet before CSI. In that case, we should cleanup the old path as soon as possible.
Fixes #
See also #1090
```release-note
```
```docs
```
=> disk: also cleanup old globalmount at unstage

deploy/chart/templates/controller.yaml
/kind cleanup
avoid quote, so that we can safely do two level of rendering
Fixes #
xref: #1137 
```release-note
NONE
```
```docs
```
=> deploy: use new header env

pkg/cloud/metadata/ack_cluster_profile.go, pkg/cloud/metadata/ack_cluster_profile_test.go, pkg/cloud/metadata/k8s.go, pkg/cloud/metadata/k8s_test.go, pkg/cloud/metadata/metadata.go, pkg/cloud/metadata/metadata_test.go
/kind cleanup
Don't fetch profile if not required.
NODE_NAME not set should not prevent fetching profile. Failing to fetch profile should not prevent trying node.
If profile is not found, it should be included in error message, instead of ignored.
Fixes #
/cc @AlbeeSo
```release-note
NONE
```
```docs
```
=> metadata: split ack-cluster-profile to another provider

deploy/chart/templates/controller.yaml, deploy/chart/values.yaml
Fixes #
add annotations on provisioner
```
annotations:
csi.alibabacloud.com/ossfs-tag: v1.88.4-d9f3917-aliyun
csi.alibabacloud.com/ossfs-updated-tag: v1.91.3-d9f3917-aliyun
```
```release-note
```
```docs
```
=> chart: add ossfs tag on provisioner

pkg/cloud/metadata/k8s.go, pkg/cloud/metadata/k8s_test.go
/kind bug
Some deployment does not populate the labels correctly, and may leave empty labels. Just ignore them and try other sources.
Fixes #
```release-note
NONE
```
```docs
```
=> metadata: ignore empty k8s node label

pkg/oss/nodeserver.go
/kind bug
Introduced by #1139
Fixes #
```release-note
```
```docs
```
=> Fix oss mount options parsing

pkg/metric/monitor_client.go
If storage-monitor is not installed, the NAS metrics collector could raise a lot of "services not found" errors.
/kind cleanup
Fixes #
```release-note
```
```docs
```
=> chore: reduce error logs from metrics collector

pkg/mounter/fuse_pod_manager.go, pkg/mounter/ossfs.go, pkg/mounter/ossfs_test.go, pkg/oss/controllerserver.go, pkg/oss/errors.go, pkg/oss/nodeserver.go, pkg/oss/nodeserver_test.go, pkg/oss/utils.go
Related conversation pls see #1111
/kind feature
Fixes #
```release-note
```
```docs
```
=> feat(OSS) rewrite: allow update token by external secret through secretRef

build/lib/init.sh, deploy/chart/templates/plugin.yaml
/kind cleanup
OSS still has updatedb related logic.
Disk with BDF still need it. But we cannot enable BDF with current helm chart. So it should be fine.
Introduce a new deploy.nodeInit to override the logic, in case if someone want to modify the yaml after it is rendered.
Fixes #
```release-note
```
```docs
```
=> deploy: only add init container for nas/oss driver

pkg/disk/cloud.go, pkg/disk/controllerserver.go, pkg/disk/nodeserver.go, pkg/disk/utils.go, test/e2e-kubernetes/eed-manifest.yaml, test/e2e-kubernetes/ephemeral-sc.yaml, test/e2e-kubernetes/run.sh
/kind bug
Fixes for EED. See commit message.
Fixes #1135 
xref https://github.com/kubernetes/kubernetes/pull/126978
```release-note
NONE
```
```docs
```
=> disk: fixes for EED

build/lib/init.sh
/kind cleanup
Remove stall vol_data.json, or we cannot remove the directory.
Iterate over the volumes, so that we are not limited by the command length.
Fixes #
```release-note
NONE
```
```docs
```
=> init: refine cleaning up old volume staging path

deploy/chart/templates/controller.yaml, deploy/chart/templates/plugin.yaml
/kind cleanup
initialDelaySeconds is ignored if it is less than periodSeconds, so just remove it. Lower periodSeconds to 10s so that we move to the next batch in 10s when rolling out updates.
Fixes #
```release-note
NONE
```
```docs
```
=> deploy: speed up the rollout

pkg/metric/nfs_stat_collector.go
/kind feature
Change unit of node_volume_capacity_bytes_total, node_volume_capacity_bytes_used, node_volume_capacity_bytes_available to bytes (nas).
Fixes #
```release-note
```
```docs
```
=> Support byte-level NAS capacity metrics

pkg/common/constants.go, pkg/disk/category.go, pkg/disk/cloud.go, pkg/disk/nodeserver.go, pkg/disk/utils.go, test/e2e-kubernetes/regional-manifest.yaml, test/e2e-kubernetes/regional-sc.yaml
/kind feature
support for regional disk
Fixes #
```release-note
Support for regional ESSD disks. To use this, add node.csi.alibabacloud.com/disktype.cloud_auto_regional=available label to the nodes that supports regional disks manually.
```
```docs
https://help.aliyun.com/zh/ecs/user-guide/regional-essd-disks (Chinese only)
```
=> support for regional disk

deploy/chart/templates/fuse.yaml
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> deploy: only install fuse namespace if OSS is enabled

deploy/chart/values.yaml
/kind bug
/kind cleanup
Fixes #
```release-note
local: fix rare mount point leak when pod is deleted immediately after creation.
```
```docs
```
=> deploy: bump image tags

test/cluster/cluster-template.jsonnet, test/cluster/cluster_setup.sh
/kind cleanup
Should fix test failures caused by "too many pods" error, which is the limitation of terway.
```release-note
NONE
```
```docs
```
=> test/cluster: use flannel & cleanups

deploy/chart/templates/controller.yaml, deploy/chart/values.yaml
/kind feature
/kind cleanup
bump csi-provisioner to v5.0.2
bump csi-resizer to v1.11.2
Fixes #
```release-note
Action required: HonorPVReclaimPolicy is enabled by default. Volume will also be deleted from the underlying storage (e.g. ECS block storage) if PV is deleted manually.
Action required: prevent-volume-mode-conversion feature flag is enabled by default. Volume mode change will be rejected when creating a PVC from a VolumeSnapshot unless the AllowVolumeModeChange annotation has been set to true. Applications relying on volume mode change when creating a PVC from VolumeSnapshot need to be updated accordingly.
```
```docs
```
=> bump csi-provisioner & csi-resizer

build/mount-proxy/Dockerfile, deploy/chart/values.yaml, pkg/mounter/ossfs.go
1.91.3.ack.3: to parse the new mountpoint and fix metrics path error.
/kind bug
Fixes #
```release-note
```
```docs
```
=> OSS: bump ossfs version to 1.91.3.ack.3 to fix metrics

deploy/chart/values.yaml
/kind bug
this is not used in helm chart, but we use it to check for image sync in CI
Fixes #
```release-note
NONE
```
```docs
```
=> deploy: fix ossfs image name

build/multi-private/Dockerfile.multi, build/multi/Dockerfile.controller, build/multi/Dockerfile.multi, build/multi/Dockerfile.multi.asi
/kind bug
to fix build failure
```
pkg/disk/cleanup.go:44:43: undefined: atomic.Bool
```
Fixes #1090
```release-note
NONE
```
```docs
```
=> bump golang to 1.19

pkg/disk/nodeserver.go
We should do this consistently regardless of snapshot. e.g. user may create a static PV from existing disk. This should save two APIServer invocation per volume.
/kind cleanup
Fixes #
```release-note
The filesystem on the disk will be expanded automatically at mount.
```
```docs
```
=> disk: do resizefs regardless of snapshot

pkg/cloud/commoninterface.go, pkg/cloud/ecsinterface.go, pkg/cloud/ecsmock.go, pkg/cloud/utils.go, pkg/cloud/utils_test.go, pkg/disk/utils.go
/kind feature
It can retrieve the endpoint of local API.
Fixes #
```release-note
NONE
```
```docs
```
=> disk: use DescribeEndpoints for internal mode

pkg/disk/cloud.go, pkg/disk/constants.go, pkg/disk/controllerserver.go, pkg/disk/nodeserver.go
/kind bug
backport of #856 #905 (only first 2 commits) #880
Fixes #
```release-note
`forceDelete` snapshot parameter is no longer respected. Now snapshot can always be deleted even if there are volumes created from it.
After 2023-10-12, ECS snapshot of ESSD is always instantly assessable, without extra fee. Related features are removed from CSI. Existing setup should continue to work. These features includes:
* VolumeSnapshotClass parameter `snapshotType=InstantAccess`
* VolumeSnapshotClass parameter `instantAccessRetentionDays`
* VolumeSnapshot annotation `storage.alibabacloud.com/ia-snapshot: true`
* VolumeSnapshot annotation `storage.alibabacloud.com/ia-snapshot-ttl`
```
```docs
```
=> [v1.26] disk snapshot force delete & instant access backport

build/lib/init.sh
/kind cleanup
This is used internally in Alibaba Cloud. And is now covered by other release platform.
Fixes #
```release-note
NONE
```
```docs
```
=> Don't install iohub-vfhp-helper

README-zh_CN.md, README.md
update readme doc
Fixes #
```release-note
```
```docs
```
=> doc: update readme

deploy/chart/templates/controller.yaml
/kind bug
Fixes #
```release-note
NONE
```
```docs
```
=> deploy: fix local external provisioner leader election args

pkg/disk/utils.go
/kind cleanup
To help user identify and fix the issue.
Fixes #
```release-note
NONE
```
```docs
```
=> disk: refine error message for rwx filesystem

pkg/disk/controllerserver.go
/kind cleanup
use timestamppb.New
rename sizeGb to sizeGB to avoid confusion
handle error of ParseInt
Fixes #
```release-note
NONE
```
```docs
```
=> disk: cleanup formatCSISnapshot

deploy/chart/values.yaml
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> bump csi-attacher to v4.6.1

build/csi-agent/Dockerfile, cmd/csi-agent/main.go, pkg/mounter/proxy/client/client.go, pkg/oss/csi_agent.go, pkg/oss/nodeserver.go
/kind feature
Fixes #
```release-note
```
```docs
```
=> Add csi-agent for oss mounting in ACS rund

deploy/chart/templates/controller.yaml, deploy/chart/templates/plugin.yaml, deploy/chart/values.yaml, pkg/oss/nodeserver.go, pkg/oss/utils.go, pkg/oss/utils_test.go, pkg/utils/util.go
Fixes #
```release-note
```
```docs
```
=> oss: support get sts endpoint from env for private cloud

deploy/chart/templates/controller.yaml
/kind cleanup
The default QPS is only 5, which is too low. We tune it up a little and see how it goes.
Ideally, We should set the QPS according to the default quota of ECS OpenAPI in the future.
Fixes #
Ideally, we should go for #1168.
```release-note
NONE
```
```docs
```
=> deploy: tune disk sidecar flow control to 2x

pkg/cloud/metadata/ecs.go, pkg/cloud/metadata/ecs_test.go, pkg/cloud/metadata/metadata_test.go
/kind feature
Fixes #1124
```release-note
Support for ECS metadata server security hardening mode
```
```docs
```
=> metadata: use ECS security hardening mode

pkg/disk/controllerserver.go
/kind cleanup
disk: reduce 1 DescribeDisks OpenAPI request on delete.
improve performance.
Fixes #
```release-note
NONE
```
```docs
```
=> disk: reduce 1 DescribeDisks OpenAPI request on delete

pkg/disk/controllerserver.go, pkg/disk/utils.go, pkg/features/features.go
to keep consistent with enable-volume-group-snapshots name of sidecar.
Fixes #
```release-note
```
```docs
```
=> rename disable-auto-snapshots feature to keep consistent with sidecar

pkg/disk/category.go, test/e2e-kubernetes/regional-sc.yaml
/kind feature
Fixes #
```release-note
Regional ESSD type renamed to cloud_regional_disk_auto
```
```docs
```
=> disk: rename regional essd to cloud_regional_disk_auto

deploy/chart/templates/controller.yaml
/kind cleanup
Like #1186 but for OSS.
Fixes #
```release-note
NONE
```
```docs
```
=> deploy: tune oss attacher flow control to 2x

build/mount-proxy/Dockerfile, pkg/mounter/ossfs.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> Fix: ossfs mime-support config not work

pkg/disk/nodeserver.go, pkg/disk/utils.go, pkg/ens/controllerserver.go, pkg/ens/nodeserver.go, pkg/mounter/fuse_pod_manager_test.go, pkg/mounter/helper.go, pkg/nas/controllerserver.go, pkg/nas/controllerserver_test.go, pkg/nas/nodeserver.go, pkg/oss/controllerserver.go, pkg/oss/nodeserver.go, pkg/utils/auth.go
/kind cleanup
Since we don't use shell in the code now, we don't need these checks. These checks are prone to false positive and sometimes blocking valid requests.
Fixes #
```release-note
Now we don't block PVCs that have special characters in annotations.
```
```docs
```
=> remove special character check

pkg/disk/utils.go, pkg/disk/utils_test.go, vendor/k8s.io/mount-utils/mount_unsupported.go, vendor/k8s.io/mount-utils/resizefs_unsupported.go
```release-note
```
```docs
```
=> Get available disk count from node annotation

deploy/chart/values-external.yaml
/kind bug
Since #1139 , we need controller for OSS to work.
Since #1105 , we can deploy controller on VK.
Fixes #
```release-note
NONE
```
```docs
```
=> deploy/external: fix for OSS driver

deploy/chart/templates/controller.yaml, deploy/chart/templates/csi-driver.yaml, deploy/chart/templates/plugin.yaml, deploy/chart/templates/rbac.yaml, deploy/chart/templates/storage-class.yaml, deploy/chart/values-edge.yaml, deploy/chart/values.yaml
/kind cleanup
This reverts commit 0352166ba66b02b1690ad059f1b5fe96f3736531.
Reverts #1201
We decided to preserve this, for our ACK Edge cluster.
Fixes #
```release-note
```
```docs
```
=> Revert "deploy: remove local"

pkg/oss/utils.go, pkg/oss/utils_test.go
/kind bug
Should not modify transmission protocol automatically for private cloud.
Fixes #
```release-note
```
```docs
```
=> Private cloud/oss protocol

deploy/chart/values.yaml
/kind cleanup
Fixes #
Should replace sidecar update in #1176 . This one use distroless as base image.
```release-note
Enable prevent-volume-mode-conversion feature flag by default.
Volume mode change will be rejected when creating a PVC from a VolumeSnapshot unless the AllowVolumeModeChange annotation has been set to true. Applications relying on volume mode change when creating a PVC from VolumeSnapshot need to be updated accordingly.
```
```docs
```
=> bump external-snapshotter to v8.1.0

pkg/disk/constants.go, pkg/disk/controllerserver.go
/kind cleanup
With external-snapshotter version v8, we do not need the extra limit logic in CSI.
related fix PR: https://github.com/kubernetes-csi/external-snapshotter/pull/1009
Fixes #
merged after #1176 
```release-note
```
```docs
```
=> cleanup: remove single snapshot request limit logic

pkg/disk/utils.go, pkg/ens/utils.go, pkg/metric/disk_stat_collector.go, pkg/metric/nfs_stat_collector.go, pkg/utils/util.go
/kind cleanup
We got a lot of junk log message
```
I1023 15:31:14.280827   28498 mount_linux.go:202] Cannot run systemd-run, assuming non-systemd OS
```
This PR try to get rid of them.
See commit message for detail
Fixes #
```release-note
NONE
```
```docs
```
=> Cleanups about mount.New()

pkg/disk/cloud.go, pkg/disk/cloud_test.go
/kind cleanup
Fixes #
Note that k8s always use ASCII names, so this should not change the behavor for k8s users.
```release-note
NONE
```
```docs
```
=> disk: support for Chinese disk name

pkg/features/features.go
/kind bug
/kind deprecation
Following up #1182
disable this since it is not working and will block resizing.
Fixes #
```release-note
DisableExpandAutoSnapshot feature gate is now defaulted to true, auto snapshot on resizing is no longer supported
```
```docs
```
=> disk: disable expand auto snapshot

pkg/common/controllerserver.go, pkg/common/interceptors.go, pkg/common/nodeserver.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> common: enable contextual logging

build/csi-agent/Dockerfile, build/mount-proxy/Dockerfile, build/multi-private/Dockerfile.multi, build/multi/Dockerfile.controller, build/multi/Dockerfile.multi, build/multi/Dockerfile.multi.asi, go.mod
/kind cleanup
Bump version of golang to 1.22.9
Fixes #
```release-note
```
```docs
```
=> Bump version of golang to 1.22.9

pkg/disk/cloud.go, pkg/disk/cloud_test.go
/kind cleanup
We can use client token to ensure that only one snapshot is created. While the
snapshots created by old versions do not have client token, we may still keep
the Describe before Create for one more version, to ensure no snapshot is
leaked.
Fixes #
```release-note
Snapshots is now created with ClientToken.
```
```docs
```
=> disk: create snapshot with client token

pkg/oss/utils.go, pkg/oss/utils_test.go
/kind bug
same as #1214
Fixes #
```release-note
```
```docs
```
=> oss: do not modify vpc100 endpoint 

pkg/disk/cloud.go, pkg/disk/controllerserver.go
/kind cleanup
external-snapshotter will create event on `volumesnapshotcontent` according to the response from CSI.
so we can remove the event recorder for snapshot.
I test with:
1. create a disk PVC but do not attach to any node.
2. create a volumesnapshot and failed with event like `The specified disk has never been attached to any instance`
3. create an app and mount with this PVC
4. succeed creating a ECS snapshot.
Fixes #
I test with external-snapshotter v8 so it is better
/hold
merged after #1176 
```release-note
```
```docs
```
=> cleanup: remove snapshot events recorder

pkg/mounter/ossfs.go, pkg/mounter/ossfs_test.go
/kind bug
role-session-name has modified to be no longer than 64 chars.
Fixes #
```release-note
```
```docs
```
=> fix: limit role-session-name for oss rrsa to 64 chars

pkg/disk/attachdetach_slot.go, pkg/disk/attachdetach_slot_test.go, pkg/disk/disk.go, pkg/utils/config.go
/kind cleanup
Only 5 concurrent detach is allowed by ECS. So limit that at our side to avoid too many conflicts.
Fixes #
```release-note
if DiskParallelAttach/DiskParallelDetach feature gates are enabled, the concurrency of attach/detach operations are still limited, defaulting to 32/5, which should match the current ECS limitation.
```
```docs
```
=> disk: control the degree of concurrency of attach/detach

pkg/oss/utils.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> oss: to keep compatible with cnfs-nas volumeas sharepath

.github/dependabot.yml
Add dependabot to csi for vulnerability auto-fix 
Fixes #
```release-note
```
```docs
```
=> Add dependabot to csi

pkg/disk/utils.go
/kind bug
Finding series-id of disk logics we have did not match new Nvme rules.  And udev rules may no longer needed.
Fixes #
```release-note
```
```docs
```
=> Fix nvme serial id check

pkg/disk/disk.go, pkg/disk/utils.go
/kind cleanup
newEcsClient is called frequently to renew the credential.
Fixes #
```release-note
NONE
```
```docs
```
=> disk: avoid access metadata server in newEcsClient

test/csi-sanity/csi-sanity-disk.yaml
/kind cleanup
To avoid the timeout of high-level pipeline.
Fixes #
```release-note
NONE
```
```docs
```
=> csi-sanity: reduce timeout

test/cluster/cluster-template.jsonnet, test/cluster/cluster_setup.sh
/kind cleanup
Fixes #
```release-note
```
```docs
```
=> test: bump cluster version

test/cluster/cluster_setup.sh
/kind bug
/kind flake
STS does not like +. Use base64url encode instead, which does not contains +.
Fixes: 90a96efa1d7734f83d1a2ca4a8352683486f324b
```release-note
NONE
```
```docs
```
=> test: fix external ID may has "+"

test/cluster/cluster-template.jsonnet, test/cluster/cluster_setup.sh
Fixes #
/hold
for EED does not have enough stock now.
```release-note
```
```docs
```
=> test/cluster: add node for EED

deploy/chart/values.yaml, test/csi-sanity/csi-sanity-disk.yaml
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> deploy: bump image version to release v1.6.1

deploy/chart/values-edge.yaml
OSS needs attacher to work
Fixes: c4c31df8b276bd3a7f8b4861e6f2e134262acec3
Fixes: #1139 
```release-note
NONE
```
```docs
```
=> deploy: enable oss controller for edge

test/cluster/cluster_setup.sh
/kind cleanup
OpenSSL outputs:
```
hex string is too long, ignoring excess
```
because here-string adds an extra new line at the end
Fixes #
```release-note
NONE
```
```docs
```
=> test: avoid warning

pkg/disk/bdf.go, pkg/disk/cloud.go, pkg/disk/controllerserver.go, pkg/disk/disk.go, pkg/disk/nodeserver.go, pkg/disk/utils.go, pkg/utils/auth.go
/kind cleanup
/kind api-change
No one is using this function now. Remove for maintainability, and reduce the possibility of security issue.
Fixes #
```release-note
Multi-tenancy support for disk driver has been removed.
```
```docs
```
=> disk: remove support for multi-tenancy

pkg/disk/nodeserver_test.go
/kind cleanup
/kind failing-test
Fix this error when running on MacOS:
rpc error: code = Internal desc = mkdir /tmpfs: read-only file system
Fixes #
```release-note
NONE
```
```docs
```
=> disk: fix unit test

pkg/disk/constants.go, pkg/disk/nodeserver.go, pkg/disk/utils.go, pkg/disk/utils_test.go
/kind bug
In case we cannot retrieve it from OpenAPI, e.g. for cn-shenzhen-a
Fixes #
```release-note
allow skip updating diskType label for existing node
```
```docs
```
=> disk: allow skip updating diskType label for existing node

go.mod, pkg/disk/controllerserver.go, pkg/disk/group_volume_snapshot_utils.go, pkg/disk/group_volume_snapshot_utils_test.go
/kind cleanup
Fixes #
This was done once in #981, but overwritten by #1176 . So let's do it again. 
```release-note
NONE
```
```docs
```
=> remove dep on old github.com/golang/protobuf

Makefile
/kind bug
/kind failing-test
tar on debian does not allow wildcards by default.
Fixes: 1929c74bf6fa040cda771df1bba6d299ea4dbb11
Fixes: #1276 
```release-note
NONE
```
```docs
```
=> fix helm install

build/csi-agent/Dockerfile, build/multi/Dockerfile.controller, build/multi/Dockerfile.multi, build/multi/Dockerfile.multi.asi, cmd/csi-agent/main.go, main.go, pkg/version/version.go
/kind cleanup
go buld -trimpath for easier reproduce.
remove build time for easier reproduce, we instead show the time from last git commit.
Fixes #
```release-note
NONE
```
```docs
```
=> Improve build reproducibility

deploy/chart/values.yaml
/kind bug
Fixes #
```release-note
Fix unbounded volumesnapshots list call on Snapshot Controller startup
```
```docs
```
=> deploy: bump snapshot controller to v8.1.1

deploy/chart/templates/plugin.yaml
/cleanup
Change the secret token name of plugin.
Fixes #
```release-note
```
```docs
```
=> Change plugin token name

deploy/chart/values.yaml
/kind bug
Add default value
Fixes #
```release-note
```
```docs
```
=> Add values

deploy/chart/templates/controller.yaml, deploy/chart/templates/plugin.yaml, deploy/chart/values-external.yaml, deploy/chart/values.yaml
/kind cleanup
Modified use newToken configuration name
Fixes #
```release-note
```
```docs
```
=> Modified use newToken configuration name

Makefile, hack/update-base-image-deps.sh
/kind feature
docker is available at prow kubekin-e2e image, and should be convenient for other contributors.
Fixes #
```release-note
NONE
```
```docs
```
=> hack: support update base image deps with docker

pkg/disk/nodeserver.go, pkg/disk/nodeserver_test.go
/kind bug
Fix NodeStageVolume idempotent issue of runD runtime
Fixes #
```release-note
```
```docs
```
=> Fix idempotent issue of runD mounted

pkg/disk/disk.go, pkg/disk/utils.go
/kind cleanup
Remove get metadata server from ECS client initialization
Fixes #
```release-note
```
```docs
```
=> Remove get metadata server from ECS client initialization

deploy/chart/templates/controller.yaml, deploy/chart/templates/plugin.yaml, deploy/chart/values.yaml
/kind cleanup
Fixes #
```release-note
```
```docs
```
=> chart: add nasEndpoint setting in values

build/multi/Dockerfile.multi
/kind cleanup
To shrink container image size
Main executable size reduced from 99M to 68M
Fixes #
```release-note
NONE
```
```docs
```
=> build: omit debug info by default

test/cluster/cluster_setup.sh
/kind bug
/kind flake
Avoid being interpreted by aliyun cli as another arg and report:
ERROR: parse failed not support flag form -0GXspllxxxxxxxx
Fixes #
```release-note
NONE
```
```docs
```
=> test: fix external ID started with "-"

build/csi-agent/Dockerfile, cmd/csi-agent/main.go, cmd/mount-proxy-server/main.go, pkg/mounter/proxy/server/alinas/mount_handler.go, pkg/mounter/proxy/server/handler.go, pkg/mounter/proxy/server/mount.go, pkg/mounter/proxy/server/ossfs/mount_handler.go, pkg/nas/csi_agent.go, pkg/nas/internal/config.go, pkg/nas/mounter.go, pkg/nas/mounter_test.go, pkg/nas/nodeserver.go
/kind feature
Fixes #
```release-note
```
```docs
```
=> csi-agent: add support for nas driver

pkg/disk/controllerserver.go
/kind cleanup
like #1323 , but for ACS
Fixes #
```release-note
NONE
```
```docs
```
=> disk: refuse to delete disk on ACS

deploy/chart/templates/controller.yaml
/kind cleanup
Tune disk related sidecar client-side flow control. See commit message for detail.
Fixes #
```release-note
NONE
```
```docs
```
=> Tune sidecar client-side flow control

pkg/disk/disk.go, pkg/disk/utils.go
Fixes #
```release-note
```
```docs
```
=> feat(disk): add region and zone labels to disk PV

deploy/chart/values.yaml
/kind bug
resolve possible lvm leakage when lvmetad crashes.
Fix deletion of inactive LV
Fixes #
```release-note
resolve possible lvm leakage when lvmetad crashes.
Fix deletion of inactive LV
```
```docs
```
=> bump local to v0.1.3

build/gather-node-deps.sh, build/multi/Dockerfile.multi, pkg/disk/sfdisk/expand.go, pkg/disk/sfdisk/expand_test.go, vendor/github.com/stretchr/testify/require/doc.go, vendor/github.com/stretchr/testify/require/forward_requirements.go, vendor/github.com/stretchr/testify/require/require.go, vendor/github.com/stretchr/testify/require/require.go.tmpl, vendor/github.com/stretchr/testify/require/require_forward.go, vendor/github.com/stretchr/testify/require/require_forward.go.tmpl, vendor/github.com/stretchr/testify/require/requirements.go, vendor/modules.txt
/kind bug
We are getting the error now:
> This disk is currently in use - repartitioning is probably a bad idea.
> Umount all file systems, and swapoff all swap partitions on this disk.
> Use the --no-reread flag to suppress this check.
Fixes: 1191e248654f7a0add1ae2b8aee474e623a5c719
Fixes #1192 
```release-note
Fixed expanding of disk with partition
```
```docs
```
=> disk: fix sfdisk for in-use disk

pkg/features/features.go, pkg/nas/internal/config.go
/kind feature
Add the `AlinasMountProxy` feature gate to support mounting Alinas or EFC through the mount proxy socket.
Fixes #
```release-note
```
```docs
```
=> feat(nas): support mounting through cnfs-alinas-daemon

pkg/common/constants.go, pkg/disk/cloud.go, pkg/disk/cloud_test.go, pkg/disk/controllerserver.go, pkg/disk/utils.go
/kind feature
Fixes #
```release-note
```
```docs
```
=> feat(disk): support creating EED for VK

pkg/disk/controllerserver.go, pkg/disk/utils.go
/kind bug
We should minimize the possibility of returning error for static volume. If we do, the disk is leaked.
Fixes #
```release-note
NONE
```
```docs
```
=> disk: skip most parameter verification for static volume

pkg/disk/utils.go
/kind bug
Clone volumeContext directly to handle external-provisioner tag omission.
Fixes #
```release-note
```
```docs
```
=> Fix tags logics

pkg/disk/utils.go, pkg/disk/utils_test.go
/kind bug
Forbid empty zoneId request for disk
Fixes #
```release-note
```
```docs
```
=> [bug]Forbid empty zoneId request for disk

main.go
this seems to be an error while resolving conflict
Fixes: 5defa96
Fixes: #993 
/kind bug
Fixes #
```release-note
NONE
```
```docs
```
=> re-enable metric for controller

build/mount-proxy/Dockerfile, deploy/chart/templates/plugin.yaml, pkg/mounter/proxy/server/alinas/driver.go
/kind feature
Fixes #
```release-note
```
```docs
```
=> Add cnfs-nas-daemon support in mount-proxy

pkg/common/interceptors.go, pkg/common/start.go
/kind cleanup
Remove the unused parameter client. Since this is intented to be used as GRPC interceptor, declare it as so, and simplify the usage.
Fixes #
```release-note
NONE
```
```docs
```
=> common: make instrumentGRPC return interceptor

pkg/utils/util.go
Fixes: 5defa961b54a444feef153e87cf6706e4f4a81b9
/kind bug
Fixes #
```release-note
NONE
```
```docs
```
=> utils: fix serviceType log

pkg/mounter/ossfs.go
/kind feature
Another solution to the problem described in #1359.
close #1359 
Fixes #
```release-note
oss: support passing mount options through environment variables.
```
```docs
```
=> oss: support passing mount options through environment variables

deploy/chart/templates/controller.yaml
/kind feature
Set controller, external provisioner, external atttacher to qps:100 burst:200.
Fixes #
```release-note
```
```docs
```
=> oss: adjust controller api qps& burst

deploy/chart/templates/_utils.tpl
/kind cleanup
We need this to generate template for ACK component
Fixes #
```release-note
NONE
```
```docs
```
=> deploy: add quote to deal with strange path

build/multi/Dockerfile.multi, hack/base-image-deps.txt
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> bump base image

build/amd/Dockerfile, build/lib/amd64-entrypoint.sh, build/multi-private/Dockerfile.multi, build/multi-private/amd64-entrypoint.sh, build/multi/Dockerfile.multi, build/multi/Dockerfile.multi.asi
/kind feature
Allow using ossfs1.91.5 for clusters < 1.26
Fixes #
```release-note
```
```docs
```
=> backport(oss): support ossfs1.91.5 by ENV

deploy/chart/values.yaml
/kind bug
/kind cleanup
Add -kube-api-qps and related args.
Bump Golang version and deps.
Fix concurrent map access
Fixes: de3297474f5bf696ac6a89ed4c556a91d2c2ab58
```release-note
NONE
```
```docs
```
=> bump local to v0.2.0

pkg/disk/disk.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> backport: allow get regionID from ENV

deploy/chart/templates/_utils.tpl, deploy/chart/templates/controller.yaml, deploy/chart/templates/plugin.yaml, deploy/chart/values.yaml
/kind feature
Lingjun nodes is not ECS, but has access to VPC network. User can also access VPC with VPN, etc.
Fixes #
```release-note
helm chart: workerRegistry is removed, please use registryVPC and deploy.network
```
```docs
```
=> deploy: add value deploy.network

pkg/common/start.go, pkg/metric/csi_grpc_exec_time_collector.go
Tell users which metrics are available. And make rate() work for the first invoke.
/kind cleanup
Tell users which metrics are available. And make rate() work for the first invoke.
Fixes #
```release-note
NONE
```
```docs
```
=> metrics: init GRPC metrics with 0 value

deploy/chart/values.yaml
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> chart: bump image version to release v1.6.3

pkg/disk/disk.go, pkg/disk/utils.go
this reverts commit ed394028de23ee53c60fb745d5db4051228ed8ca
This is behind a env for 3 years, and we have not seen real usage of this feature.
Fixes #
```release-note
NONE
```
```docs
```
=> revert "support multi-zone node for virtual node"

pkg/disk/utils.go, pkg/oss/utils.go, pkg/oss/utils_test.go, pkg/utils/global.go
/kind bug
Fixes #1407 
```release-note
oss: automatically set internal endpoint only if ALIBABA_CLOUD_NETWORK_TYPE is set to "vpc"
```
```docs
```
=> oss: use internal endpoint only for VPC network

test/csi-sanity/csi-sanity-disk.yaml
/kind bug
We don't have shell in CSI container now, we cannot fetch the report from the container. So just write it to hostPath, then we can fetch it with ssh.
Fixes failing to collect junit report for csi-sanity
```release-note
NONE
```
```docs
```
=> write csi-sanity junit report to hostPath

docs/install.md
Now that nas driver needs to call OpenAPI, it is required to set correct regionID.
Fixes #
```release-note
NONE
```
```docs
```
=> docs: non-ECS cluster needs regionID to be specified

pkg/utils/auth.go
/kind bug
SDK has changed its error message. SDK does not expose error object, so we have no better way than compare error message.
Fixes: 9b04ffc7e3256804c0ccd12bbd87687cf6b65a54
```release-note
NONE
```
```docs
```
=> adapt to error message change

pkg/nas/accesspoint_controller.go, pkg/nas/filesystem_controller.go, pkg/nas/filesystem_controller_test.go, pkg/nas/internal/config.go, pkg/nas/subpath_controller.go
/kind cleanup
Query zone/region/cluster ID from cloud/metadata package, to support ECS IMDSv2.
Fixes #
/hold
based on #1405 . Merge after that.
Reviewer: please just review the last commit.
```release-note
NONE
```
```docs
```
=> nas: use cloud/metadata

pkg/disk/bdf.go, pkg/disk/cloud.go, pkg/disk/constants.go, pkg/disk/controllerserver.go, pkg/disk/group_volume_snapshot_utils.go, pkg/disk/nodeserver.go, pkg/disk/utils.go, pkg/metric/common.go, pkg/metric/nfs_stat_collector.go, pkg/metric/utils.go, pkg/nas/filesystem_controller.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> batch fix vet and go-staticcheck warnings

pkg/disk/nodeserver.go, pkg/disk/sfdisk/expand.go
/kind bug
Fixes #
```release-note
NONE
```
```docs
```
=> disk: fix expand parted

deploy/chart/templates/plugin.yaml, deploy/chart/values.yaml
/kind cleanup
And enable json logging for it.
Switch to distroless base image.
Reduce the image size from 16M to 7.5M.
Fixes #
```release-note
NONE
```
```docs
```
=> bump registrar to v2.14.0

docs/oss.md
Co-authored-by: DahuK <dahu.kdh@alibaba-inc.com>
add OSS client selection reference in doc/oss.md
Fixes #
```release-note
```
```docs
```
=> docs(OSS): add client selection reference in doc/oss.md

pkg/metric/nfs_stat_collector.go
/kind bug
prometheus client will check for consistency. It will prevent inconsistent metrics from reporting.
Fixes: 660858229789ca8ca30e5a875e544f9e6994564b
Fixes #1046
```release-note
Fixes NAS metrics reporting
```
```docs
```
=> metric/nas: fix inconsistency with disk

pkg/disk/disk.go, pkg/metric/nfs_stat_collector.go, pkg/nas/internal/config.go, pkg/options/genericoptions.go, pkg/options/genericoptions_test.go, pkg/oss/oss.go
/kind bug
SnapClient does not support Protobuf ContentType, change it back to JSON 
Fixes #
```release-note
```
```docs
```
=> fix: use json content-type for snapshotclient, fixing autosnapshot issues

pkg/disk/utils.go, pkg/disk/utils_test.go, vendor/k8s.io/klog/v2/ktesting/options.go, vendor/k8s.io/klog/v2/ktesting/setup.go, vendor/k8s.io/klog/v2/ktesting/testinglogger.go, vendor/modules.txt
/kind feature
Fixes #
```release-note
disk: automatic label nodes with regional ESSD support
```
```docs
```
=> disk: automatic label nodes with regional ESSD support

pkg/nas/utils.go
/kind feature
Fixes #
```release-note
```
```docs
```
=> feat(compatibility): support mounting bmcpfs vsc mount target using nas driver

build/build-all-multi.sh, build/multi/Dockerfile.multi, deploy/chart/templates/controller.yaml, main.go
/kind cleanup
use non-root user
readOnlyRootFilesystem: true
allowPrivilegeEscalation: false
Fixes #
```release-note
NONE
```
```docs
```
=> controller deploy security hardening

build/csi-agent/Dockerfile
/kind feature
CSI-agent support ossfs2.0 .
Fixes #
```release-note
```
```docs
```
=> agent: csi-agent support ossfs2.0

pkg/mounter/utils/fuse_pod_manager.go, pkg/mounter/utils/helper.go, pkg/mounter/utils/helper_test.go
/kind bug
Allow using PV name / volumeHandle longer than 63 chars.
Fixes #
```release-note
```
New label is like 
```
csi-fuse-ossfs-nhcln   1/1     Running   0          81s   alibabacloud.com/drain-pod=skip,csi.alibabacloud.com/fuse-type=ossfs,csi.alibabacloud.com/mount-path-hash=849f9d6c5,csi.alibabacloud.com/volume-id=6836cf13bac400e9105071cd6af47084dfacad4e5e302c94bfed24e013afb73
```
```docs
```
=> oss: if the volumeId is too long for label value, use sha1

pkg/disk/controllerserver.go, pkg/disk/nodeserver.go
/kind feature
We are not creating the auto snapshot now, so remove this delete logic.
Avoid OpenAPI authorization on node.
```release-note
Disk expand auto snapshot will not be deleted after expansion finished. It will still be deleted automatically after retention days.
```
```docs
```
=> disk: do not delete expand auto snapshot

pkg/disk/device_manager.go
Fixes #
```release-note
NONE
```
```docs
```
=> disk: add comment about udev fallback branch

deploy/chart/templates/controller.yaml, deploy/chart/values.yaml
/kind cleanup
Serve additional leader election, work queue, process, and Go runtime metrics
Move RecoverVolumeExpansionFailure to beta and enabled by default
Fixes #
```release-note
Serve additional leader election, work queue, process, and Go runtime metrics for external-resizer
Move RecoverVolumeExpansionFailure to beta and enabled by default
```
```docs
```
=> bump resizer to v1.14.0-aliyun

test/cluster/cluster-template.jsonnet
/kind cleanup
/kind failing-test
Fixes #
```release-note
NONE
```
```docs
```
=> bump test cluster to 1.33.3

pkg/disk/nodeserver.go
/kind cleanup
This can happen if user detached the disk manually. Make it easier for debug.
Fixes #
```release-note
NONE
```
```docs
```
=> disk: output path when checking device

pkg/disk/cloud.go
/kind feature
Fixes #
```release-note
NONE
```
```docs
```
=> disk: call force attach on Detaching status

pkg/cloud/metadata/ecs.go, pkg/cloud/metadata/ecs_dynamic.go, pkg/cloud/metadata/ecs_test.go, pkg/cloud/metadata/imds/imds_client.go, pkg/cloud/metadata/imds/imds_client_test.go, pkg/cloud/metadata/metadata.go, pkg/cloud/metadata/metadata_test.go, pkg/oss/controllerserver.go, pkg/oss/nodeserver.go, pkg/oss/utils.go, pkg/oss/utils_test.go, pkg/utils/util.go
/kind feature
Fixes #
```release-note
ossfs support for fetch role name with IMDS v2
```
```docs
```
=> oss: fetch RAM role name with metadata

pkg/oss/controllerserver.go, pkg/oss/nodeserver.go
Fixes #
```release-note
```
```docs
```
=> cleanup(oss): remove too long debug logs

deploy/chart/templates/controller.yaml, deploy/chart/values.yaml
/kind bug
Fix:
time="2025-07-31T07:14:52Z" level=fatal msg="WriteFile caCertFile is failed, caCertFile:/tls/local/grpc/ca_cert.pem, err:open /tls/local/grpc/ca_cert.pem: no such file or directory"
Fixes: 31e4961dbd7760fcb89ea765812c1cfcc25b006d
```release-note
NONE
```
```docs
```
=> bump local to v0.2.1

pkg/oss/nodeserver.go
/kind bug
Previously ossfs RRSA options are appended to all oss mount situations, causing mount failure   when using RRSA in ACK.
Fix OSS RRSA mount failure: add ossfs RRSA options only when cmd mounter is used.
```release-note
```
```docs
```
=> Fix oss rrsa mount issue

pkg/credentials/credential.go, pkg/credentials/credential_test.go, pkg/credentials/managed_token.go, pkg/credentials/managed_token_test.go, pkg/utils/auth.go, pkg/utils/crypto/ramtoken.go, pkg/utils/crypto/ramtoken_test.go, pkg/utils/crypto/testing/test_ramtoken.go
/kind cleanup
Part 1 of #873
only introduce the infrastructure and not used in any driver yet.
Fixes #
```release-note
NONE
```
```docs
ACCESS_KEY_ID and related environment variables are deprecated, please use ALIBABA_CLOUD_ACCESS_KEY_ID and related instead.
```
=> Refactor credential acquisition (part 1)

pkg/oss/utils.go
/kind bug
Fixes: b86808e7f79bf13205ed02268215909c8bd3d5d8
```release-note
OSS now tolerate unknown regionID again.
```
```docs
```
=> oss: tolerate no regionID

.gitignore, docs/bmcpfs-helm-readme-zh.md, docs/bmcpfs-helm-readme.md
Add bmcpfs usage guides
Fixes #
```release-note
```
```docs
```
=> Add bmcpfs docs

build/csi-agent/Dockerfile, build/mount-proxy/Dockerfile, build/multi/Dockerfile.multi, build/multi/Dockerfile.multi.asi, go.mod, pkg/bmcpfs/controllerserver.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> bump golang version to 1.24.6

pkg/disk/bdf.go
/kind bug
1ded is vendor ID of Alibaba, but we also see 1af4 (Red Hat) in the wild. So we just don't check vendor ID.
Fixes #
```release-note
NONE
```
```docs
```
=> disk: read sysfs to determine driver type

deploy/charts/alibaba-cloud-csi-driver/values.yaml
/kind bug
Fixes #
```release-note
ignore "type" from PVC label/annotation
```
```docs
```
=> bump external provisioner

pkg/mounter/proxy/server/ossfs/driver.go, pkg/mounter/proxy/server/ossfs2/driver.go, pkg/mounter/proxy/server/switchable_buffer.go
/kind feature
Fixes #
Add stderr messages from ossfs to response from mount-proxy server. NodePublish will seal this error and return.
```release-note
```
```docs
```
=> mounter: print stderr to fuse pod if exited with error
